//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generation date: 05.01.2024 23:02:18
namespace Sungero.IntegrationService.Models.Generated.ExchangeCore
{
    /// <summary>
    /// There are no comments for IBusinessUnitBoxFormalizedPoAInfosDtoSingle in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("IBusinessUnitBoxFormalizedPoAInfosDtoSingle")]
    public partial class IBusinessUnitBoxFormalizedPoAInfosDtoSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<IBusinessUnitBoxFormalizedPoAInfosDto>
    {
        /// <summary>
        /// Initialize a new IBusinessUnitBoxFormalizedPoAInfosDtoSingle object.
        /// </summary>
        public IBusinessUnitBoxFormalizedPoAInfosDtoSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new IBusinessUnitBoxFormalizedPoAInfosDtoSingle object.
        /// </summary>
        public IBusinessUnitBoxFormalizedPoAInfosDtoSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new IBusinessUnitBoxFormalizedPoAInfosDtoSingle object.
        /// </summary>
        public IBusinessUnitBoxFormalizedPoAInfosDtoSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<IBusinessUnitBoxFormalizedPoAInfosDto> query)
            : base(query) {}

        /// <summary>
        /// There are no comments for BusinessUnitBox in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("BusinessUnitBox")]
        public virtual global::Sungero.IntegrationService.Models.Generated.ExchangeCore.IBusinessUnitBoxDtoSingle BusinessUnitBox
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._BusinessUnitBox == null))
                {
                    this._BusinessUnitBox = new global::Sungero.IntegrationService.Models.Generated.ExchangeCore.IBusinessUnitBoxDtoSingle(this.Context, GetPath("BusinessUnitBox"));
                }
                return this._BusinessUnitBox;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Sungero.IntegrationService.Models.Generated.ExchangeCore.IBusinessUnitBoxDtoSingle _BusinessUnitBox;
    }
    /// <summary>
    /// There are no comments for IBusinessUnitBoxFormalizedPoAInfosDto in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("Id")]
    [global::Microsoft.OData.Client.OriginalNameAttribute("IBusinessUnitBoxFormalizedPoAInfosDto")]
    public partial class IBusinessUnitBoxFormalizedPoAInfosDto : global::Microsoft.OData.Client.BaseEntityType, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new IBusinessUnitBoxFormalizedPoAInfosDto object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public static IBusinessUnitBoxFormalizedPoAInfosDto CreateIBusinessUnitBoxFormalizedPoAInfosDto(long ID)
        {
            IBusinessUnitBoxFormalizedPoAInfosDto iBusinessUnitBoxFormalizedPoAInfosDto = new IBusinessUnitBoxFormalizedPoAInfosDto();
            iBusinessUnitBoxFormalizedPoAInfosDto.Id = ID;
            return iBusinessUnitBoxFormalizedPoAInfosDto;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("Id")]
        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "Id is required.")]
        public virtual long Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private long _Id;
        partial void OnIdChanging(long value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property UnifiedRegistrationNumber in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("UnifiedRegistrationNumber")]
        public virtual string UnifiedRegistrationNumber
        {
            get
            {
                return this._UnifiedRegistrationNumber;
            }
            set
            {
                this.OnUnifiedRegistrationNumberChanging(value);
                this._UnifiedRegistrationNumber = value;
                this.OnUnifiedRegistrationNumberChanged();
                this.OnPropertyChanged("UnifiedRegistrationNumber");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _UnifiedRegistrationNumber;
        partial void OnUnifiedRegistrationNumberChanging(string value);
        partial void OnUnifiedRegistrationNumberChanged();
        /// <summary>
        /// There are no comments for Property Url in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("Url")]
        public virtual string Url
        {
            get
            {
                return this._Url;
            }
            set
            {
                this.OnUrlChanging(value);
                this._Url = value;
                this.OnUrlChanged();
                this.OnPropertyChanged("Url");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _Url;
        partial void OnUrlChanging(string value);
        partial void OnUrlChanged();
        /// <summary>
        /// There are no comments for Property Description in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("Description")]
        public virtual string Description
        {
            get
            {
                return this._Description;
            }
            set
            {
                this.OnDescriptionChanging(value);
                this._Description = value;
                this.OnDescriptionChanged();
                this.OnPropertyChanged("Description");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _Description;
        partial void OnDescriptionChanging(string value);
        partial void OnDescriptionChanged();
        /// <summary>
        /// There are no comments for Property BusinessUnitBox in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("BusinessUnitBox")]
        public virtual global::Sungero.IntegrationService.Models.Generated.ExchangeCore.IBusinessUnitBoxDto BusinessUnitBox
        {
            get
            {
                return this._BusinessUnitBox;
            }
            set
            {
                this.OnBusinessUnitBoxChanging(value);
                this._BusinessUnitBox = value;
                this.OnBusinessUnitBoxChanged();
                this.OnPropertyChanged("BusinessUnitBox");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Sungero.IntegrationService.Models.Generated.ExchangeCore.IBusinessUnitBoxDto _BusinessUnitBox;
        partial void OnBusinessUnitBoxChanging(global::Sungero.IntegrationService.Models.Generated.ExchangeCore.IBusinessUnitBoxDto value);
        partial void OnBusinessUnitBoxChanged();
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
}
