//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generation date: 05.01.2024 23:02:18
namespace Sungero.IntegrationService.Models.Generated.ExchangeCore
{
    /// <summary>
    /// There are no comments for IBusinessUnitBoxExchangeServiceCertificatesDtoSingle in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("IBusinessUnitBoxExchangeServiceCertificatesDtoSingle")]
    public partial class IBusinessUnitBoxExchangeServiceCertificatesDtoSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<IBusinessUnitBoxExchangeServiceCertificatesDto>
    {
        /// <summary>
        /// Initialize a new IBusinessUnitBoxExchangeServiceCertificatesDtoSingle object.
        /// </summary>
        public IBusinessUnitBoxExchangeServiceCertificatesDtoSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new IBusinessUnitBoxExchangeServiceCertificatesDtoSingle object.
        /// </summary>
        public IBusinessUnitBoxExchangeServiceCertificatesDtoSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new IBusinessUnitBoxExchangeServiceCertificatesDtoSingle object.
        /// </summary>
        public IBusinessUnitBoxExchangeServiceCertificatesDtoSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<IBusinessUnitBoxExchangeServiceCertificatesDto> query)
            : base(query) {}

        /// <summary>
        /// There are no comments for BusinessUnitBox in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("BusinessUnitBox")]
        public virtual global::Sungero.IntegrationService.Models.Generated.ExchangeCore.IBusinessUnitBoxDtoSingle BusinessUnitBox
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._BusinessUnitBox == null))
                {
                    this._BusinessUnitBox = new global::Sungero.IntegrationService.Models.Generated.ExchangeCore.IBusinessUnitBoxDtoSingle(this.Context, GetPath("BusinessUnitBox"));
                }
                return this._BusinessUnitBox;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Sungero.IntegrationService.Models.Generated.ExchangeCore.IBusinessUnitBoxDtoSingle _BusinessUnitBox;
        /// <summary>
        /// There are no comments for Certificate in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Certificate")]
        public virtual global::Sungero.IntegrationService.Models.Generated.CoreEntities.ICertificateDtoSingle Certificate
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._Certificate == null))
                {
                    this._Certificate = new global::Sungero.IntegrationService.Models.Generated.CoreEntities.ICertificateDtoSingle(this.Context, GetPath("Certificate"));
                }
                return this._Certificate;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Sungero.IntegrationService.Models.Generated.CoreEntities.ICertificateDtoSingle _Certificate;
    }
    /// <summary>
    /// There are no comments for IBusinessUnitBoxExchangeServiceCertificatesDto in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("Id")]
    [global::Microsoft.OData.Client.OriginalNameAttribute("IBusinessUnitBoxExchangeServiceCertificatesDto")]
    public partial class IBusinessUnitBoxExchangeServiceCertificatesDto : global::Microsoft.OData.Client.BaseEntityType, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new IBusinessUnitBoxExchangeServiceCertificatesDto object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public static IBusinessUnitBoxExchangeServiceCertificatesDto CreateIBusinessUnitBoxExchangeServiceCertificatesDto(long ID)
        {
            IBusinessUnitBoxExchangeServiceCertificatesDto iBusinessUnitBoxExchangeServiceCertificatesDto = new IBusinessUnitBoxExchangeServiceCertificatesDto();
            iBusinessUnitBoxExchangeServiceCertificatesDto.Id = ID;
            return iBusinessUnitBoxExchangeServiceCertificatesDto;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("Id")]
        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "Id is required.")]
        public virtual long Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private long _Id;
        partial void OnIdChanging(long value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property BusinessUnitBox in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("BusinessUnitBox")]
        public virtual global::Sungero.IntegrationService.Models.Generated.ExchangeCore.IBusinessUnitBoxDto BusinessUnitBox
        {
            get
            {
                return this._BusinessUnitBox;
            }
            set
            {
                this.OnBusinessUnitBoxChanging(value);
                this._BusinessUnitBox = value;
                this.OnBusinessUnitBoxChanged();
                this.OnPropertyChanged("BusinessUnitBox");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Sungero.IntegrationService.Models.Generated.ExchangeCore.IBusinessUnitBoxDto _BusinessUnitBox;
        partial void OnBusinessUnitBoxChanging(global::Sungero.IntegrationService.Models.Generated.ExchangeCore.IBusinessUnitBoxDto value);
        partial void OnBusinessUnitBoxChanged();
        /// <summary>
        /// There are no comments for Property Certificate in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("Certificate")]
        public virtual global::Sungero.IntegrationService.Models.Generated.CoreEntities.ICertificateDto Certificate
        {
            get
            {
                return this._Certificate;
            }
            set
            {
                this.OnCertificateChanging(value);
                this._Certificate = value;
                this.OnCertificateChanged();
                this.OnPropertyChanged("Certificate");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Sungero.IntegrationService.Models.Generated.CoreEntities.ICertificateDto _Certificate;
        partial void OnCertificateChanging(global::Sungero.IntegrationService.Models.Generated.CoreEntities.ICertificateDto value);
        partial void OnCertificateChanged();
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
}
