//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generation date: 26.11.2023 2:59:27
namespace Sungero.IntegrationService.Models.Generated.ExchangeCore
{
    /// <summary>
    /// There are no comments for IBusinessUnitBoxDtoSingle in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("IBusinessUnitBoxDtoSingle")]
    public partial class IBusinessUnitBoxDtoSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<IBusinessUnitBoxDto>
    {
        /// <summary>
        /// Initialize a new IBusinessUnitBoxDtoSingle object.
        /// </summary>
        public IBusinessUnitBoxDtoSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new IBusinessUnitBoxDtoSingle object.
        /// </summary>
        public IBusinessUnitBoxDtoSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new IBusinessUnitBoxDtoSingle object.
        /// </summary>
        public IBusinessUnitBoxDtoSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<IBusinessUnitBoxDto> query)
            : base(query) {}

        /// <summary>
        /// There are no comments for BusinessUnit in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("BusinessUnit")]
        public virtual global::Sungero.IntegrationService.Models.Generated.Company.IBusinessUnitDtoSingle BusinessUnit
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._BusinessUnit == null))
                {
                    this._BusinessUnit = new global::Sungero.IntegrationService.Models.Generated.Company.IBusinessUnitDtoSingle(this.Context, GetPath("BusinessUnit"));
                }
                return this._BusinessUnit;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Sungero.IntegrationService.Models.Generated.Company.IBusinessUnitDtoSingle _BusinessUnit;
        /// <summary>
        /// There are no comments for ExchangeService in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("ExchangeService")]
        public virtual global::Sungero.IntegrationService.Models.Generated.ExchangeCore.IExchangeServiceDtoSingle ExchangeService
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._ExchangeService == null))
                {
                    this._ExchangeService = new global::Sungero.IntegrationService.Models.Generated.ExchangeCore.IExchangeServiceDtoSingle(this.Context, GetPath("ExchangeService"));
                }
                return this._ExchangeService;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Sungero.IntegrationService.Models.Generated.ExchangeCore.IExchangeServiceDtoSingle _ExchangeService;
        /// <summary>
        /// There are no comments for ExchangeServiceCertificates in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("ExchangeServiceCertificates")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<global::Sungero.IntegrationService.Models.Generated.ExchangeCore.IBusinessUnitBoxExchangeServiceCertificatesDto> ExchangeServiceCertificates
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._ExchangeServiceCertificates == null))
                {
                    this._ExchangeServiceCertificates = Context.CreateQuery<global::Sungero.IntegrationService.Models.Generated.ExchangeCore.IBusinessUnitBoxExchangeServiceCertificatesDto>(GetPath("ExchangeServiceCertificates"));
                }
                return this._ExchangeServiceCertificates;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::Sungero.IntegrationService.Models.Generated.ExchangeCore.IBusinessUnitBoxExchangeServiceCertificatesDto> _ExchangeServiceCertificates;
        /// <summary>
        /// There are no comments for CertificateReceiptNotifications in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("CertificateReceiptNotifications")]
        public virtual global::Sungero.IntegrationService.Models.Generated.CoreEntities.ICertificateDtoSingle CertificateReceiptNotifications
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._CertificateReceiptNotifications == null))
                {
                    this._CertificateReceiptNotifications = new global::Sungero.IntegrationService.Models.Generated.CoreEntities.ICertificateDtoSingle(this.Context, GetPath("CertificateReceiptNotifications"));
                }
                return this._CertificateReceiptNotifications;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Sungero.IntegrationService.Models.Generated.CoreEntities.ICertificateDtoSingle _CertificateReceiptNotifications;
        /// <summary>
        /// There are no comments for FormalizedPoAInfos in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("FormalizedPoAInfos")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<global::Sungero.IntegrationService.Models.Generated.ExchangeCore.IBusinessUnitBoxFormalizedPoAInfosDto> FormalizedPoAInfos
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._FormalizedPoAInfos == null))
                {
                    this._FormalizedPoAInfos = Context.CreateQuery<global::Sungero.IntegrationService.Models.Generated.ExchangeCore.IBusinessUnitBoxFormalizedPoAInfosDto>(GetPath("FormalizedPoAInfos"));
                }
                return this._FormalizedPoAInfos;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::Sungero.IntegrationService.Models.Generated.ExchangeCore.IBusinessUnitBoxFormalizedPoAInfosDto> _FormalizedPoAInfos;
        /// <summary>
        /// There are no comments for Responsible in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Responsible")]
        public virtual global::Sungero.IntegrationService.Models.Generated.DreamSolution.IEmployeeDtoSingle Responsible
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._Responsible == null))
                {
                    this._Responsible = new global::Sungero.IntegrationService.Models.Generated.DreamSolution.IEmployeeDtoSingle(this.Context, GetPath("Responsible"));
                }
                return this._Responsible;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Sungero.IntegrationService.Models.Generated.DreamSolution.IEmployeeDtoSingle _Responsible;
    }
    /// <summary>
    /// There are no comments for IBusinessUnitBoxDto in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("Id")]
    [global::Microsoft.OData.Client.OriginalNameAttribute("IBusinessUnitBoxDto")]
    public partial class IBusinessUnitBoxDto : IBoxBaseDto
    {
        /// <summary>
        /// Create a new IBusinessUnitBoxDto object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public static IBusinessUnitBoxDto CreateIBusinessUnitBoxDto(long ID)
        {
            IBusinessUnitBoxDto iBusinessUnitBoxDto = new IBusinessUnitBoxDto();
            iBusinessUnitBoxDto.Id = ID;
            return iBusinessUnitBoxDto;
        }
        /// <summary>
        /// There are no comments for Property Login in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("Login")]
        public virtual string Login
        {
            get
            {
                return this._Login;
            }
            set
            {
                this.OnLoginChanging(value);
                this._Login = value;
                this.OnLoginChanged();
                this.OnPropertyChanged("Login");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _Login;
        partial void OnLoginChanging(string value);
        partial void OnLoginChanged();
        /// <summary>
        /// There are no comments for Property Password in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("Password")]
        public virtual string Password
        {
            get
            {
                return this._Password;
            }
            set
            {
                this.OnPasswordChanging(value);
                this._Password = value;
                this.OnPasswordChanged();
                this.OnPropertyChanged("Password");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _Password;
        partial void OnPasswordChanging(string value);
        partial void OnPasswordChanged();
        /// <summary>
        /// There are no comments for Property OrganizationId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("OrganizationId")]
        public virtual string OrganizationId
        {
            get
            {
                return this._OrganizationId;
            }
            set
            {
                this.OnOrganizationIdChanging(value);
                this._OrganizationId = value;
                this.OnOrganizationIdChanged();
                this.OnPropertyChanged("OrganizationId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _OrganizationId;
        partial void OnOrganizationIdChanging(string value);
        partial void OnOrganizationIdChanged();
        /// <summary>
        /// There are no comments for Property HasExchangeServiceCertificates in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("HasExchangeServiceCertificates")]
        public virtual global::System.Nullable<bool> HasExchangeServiceCertificates
        {
            get
            {
                return this._HasExchangeServiceCertificates;
            }
            set
            {
                this.OnHasExchangeServiceCertificatesChanging(value);
                this._HasExchangeServiceCertificates = value;
                this.OnHasExchangeServiceCertificatesChanged();
                this.OnPropertyChanged("HasExchangeServiceCertificates");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<bool> _HasExchangeServiceCertificates;
        partial void OnHasExchangeServiceCertificatesChanging(global::System.Nullable<bool> value);
        partial void OnHasExchangeServiceCertificatesChanged();
        /// <summary>
        /// There are no comments for Property FtsId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("FtsId")]
        public virtual string FtsId
        {
            get
            {
                return this._FtsId;
            }
            set
            {
                this.OnFtsIdChanging(value);
                this._FtsId = value;
                this.OnFtsIdChanged();
                this.OnPropertyChanged("FtsId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _FtsId;
        partial void OnFtsIdChanging(string value);
        partial void OnFtsIdChanged();
        /// <summary>
        /// There are no comments for Property BusinessUnit in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("BusinessUnit")]
        public virtual global::Sungero.IntegrationService.Models.Generated.Company.IBusinessUnitDto BusinessUnit
        {
            get
            {
                return this._BusinessUnit;
            }
            set
            {
                this.OnBusinessUnitChanging(value);
                this._BusinessUnit = value;
                this.OnBusinessUnitChanged();
                this.OnPropertyChanged("BusinessUnit");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Sungero.IntegrationService.Models.Generated.Company.IBusinessUnitDto _BusinessUnit;
        partial void OnBusinessUnitChanging(global::Sungero.IntegrationService.Models.Generated.Company.IBusinessUnitDto value);
        partial void OnBusinessUnitChanged();
        /// <summary>
        /// There are no comments for Property ExchangeService in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("ExchangeService")]
        public virtual global::Sungero.IntegrationService.Models.Generated.ExchangeCore.IExchangeServiceDto ExchangeService
        {
            get
            {
                return this._ExchangeService;
            }
            set
            {
                this.OnExchangeServiceChanging(value);
                this._ExchangeService = value;
                this.OnExchangeServiceChanged();
                this.OnPropertyChanged("ExchangeService");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Sungero.IntegrationService.Models.Generated.ExchangeCore.IExchangeServiceDto _ExchangeService;
        partial void OnExchangeServiceChanging(global::Sungero.IntegrationService.Models.Generated.ExchangeCore.IExchangeServiceDto value);
        partial void OnExchangeServiceChanged();
        /// <summary>
        /// There are no comments for Property ExchangeServiceCertificates in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("ExchangeServiceCertificates")]
        public virtual global::Microsoft.OData.Client.DataServiceCollection<global::Sungero.IntegrationService.Models.Generated.ExchangeCore.IBusinessUnitBoxExchangeServiceCertificatesDto> ExchangeServiceCertificates
        {
            get
            {
                return this._ExchangeServiceCertificates;
            }
            set
            {
                this.OnExchangeServiceCertificatesChanging(value);
                this._ExchangeServiceCertificates = value;
                this.OnExchangeServiceCertificatesChanged();
                this.OnPropertyChanged("ExchangeServiceCertificates");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceCollection<global::Sungero.IntegrationService.Models.Generated.ExchangeCore.IBusinessUnitBoxExchangeServiceCertificatesDto> _ExchangeServiceCertificates = new global::Microsoft.OData.Client.DataServiceCollection<global::Sungero.IntegrationService.Models.Generated.ExchangeCore.IBusinessUnitBoxExchangeServiceCertificatesDto>(null, global::Microsoft.OData.Client.TrackingMode.None);
        partial void OnExchangeServiceCertificatesChanging(global::Microsoft.OData.Client.DataServiceCollection<global::Sungero.IntegrationService.Models.Generated.ExchangeCore.IBusinessUnitBoxExchangeServiceCertificatesDto> value);
        partial void OnExchangeServiceCertificatesChanged();
        /// <summary>
        /// There are no comments for Property CertificateReceiptNotifications in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("CertificateReceiptNotifications")]
        public virtual global::Sungero.IntegrationService.Models.Generated.CoreEntities.ICertificateDto CertificateReceiptNotifications
        {
            get
            {
                return this._CertificateReceiptNotifications;
            }
            set
            {
                this.OnCertificateReceiptNotificationsChanging(value);
                this._CertificateReceiptNotifications = value;
                this.OnCertificateReceiptNotificationsChanged();
                this.OnPropertyChanged("CertificateReceiptNotifications");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Sungero.IntegrationService.Models.Generated.CoreEntities.ICertificateDto _CertificateReceiptNotifications;
        partial void OnCertificateReceiptNotificationsChanging(global::Sungero.IntegrationService.Models.Generated.CoreEntities.ICertificateDto value);
        partial void OnCertificateReceiptNotificationsChanged();
        /// <summary>
        /// There are no comments for Property FormalizedPoAInfos in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("FormalizedPoAInfos")]
        public virtual global::Microsoft.OData.Client.DataServiceCollection<global::Sungero.IntegrationService.Models.Generated.ExchangeCore.IBusinessUnitBoxFormalizedPoAInfosDto> FormalizedPoAInfos
        {
            get
            {
                return this._FormalizedPoAInfos;
            }
            set
            {
                this.OnFormalizedPoAInfosChanging(value);
                this._FormalizedPoAInfos = value;
                this.OnFormalizedPoAInfosChanged();
                this.OnPropertyChanged("FormalizedPoAInfos");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceCollection<global::Sungero.IntegrationService.Models.Generated.ExchangeCore.IBusinessUnitBoxFormalizedPoAInfosDto> _FormalizedPoAInfos = new global::Microsoft.OData.Client.DataServiceCollection<global::Sungero.IntegrationService.Models.Generated.ExchangeCore.IBusinessUnitBoxFormalizedPoAInfosDto>(null, global::Microsoft.OData.Client.TrackingMode.None);
        partial void OnFormalizedPoAInfosChanging(global::Microsoft.OData.Client.DataServiceCollection<global::Sungero.IntegrationService.Models.Generated.ExchangeCore.IBusinessUnitBoxFormalizedPoAInfosDto> value);
        partial void OnFormalizedPoAInfosChanged();
    }
}
