//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generation date: 05.01.2024 23:02:18
namespace Sungero.IntegrationService.Models.Generated.Company
{
    /// <summary>
    /// There are no comments for IDepartmentDtoSingle in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("IDepartmentDtoSingle")]
    public partial class IDepartmentDtoSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<IDepartmentDto>
    {
        /// <summary>
        /// Initialize a new IDepartmentDtoSingle object.
        /// </summary>
        public IDepartmentDtoSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new IDepartmentDtoSingle object.
        /// </summary>
        public IDepartmentDtoSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new IDepartmentDtoSingle object.
        /// </summary>
        public IDepartmentDtoSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<IDepartmentDto> query)
            : base(query) {}

        /// <summary>
        /// There are no comments for Manager in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Manager")]
        public virtual global::Sungero.IntegrationService.Models.Generated.NewDreamSolution.IEmployeeDtoSingle Manager
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._Manager == null))
                {
                    this._Manager = new global::Sungero.IntegrationService.Models.Generated.NewDreamSolution.IEmployeeDtoSingle(this.Context, GetPath("Manager"));
                }
                return this._Manager;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Sungero.IntegrationService.Models.Generated.NewDreamSolution.IEmployeeDtoSingle _Manager;
        /// <summary>
        /// There are no comments for HeadOffice in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("HeadOffice")]
        public virtual global::Sungero.IntegrationService.Models.Generated.Company.IDepartmentDtoSingle HeadOffice
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._HeadOffice == null))
                {
                    this._HeadOffice = new global::Sungero.IntegrationService.Models.Generated.Company.IDepartmentDtoSingle(this.Context, GetPath("HeadOffice"));
                }
                return this._HeadOffice;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Sungero.IntegrationService.Models.Generated.Company.IDepartmentDtoSingle _HeadOffice;
        /// <summary>
        /// There are no comments for BusinessUnit in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("BusinessUnit")]
        public virtual global::Sungero.IntegrationService.Models.Generated.Company.IBusinessUnitDtoSingle BusinessUnit
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._BusinessUnit == null))
                {
                    this._BusinessUnit = new global::Sungero.IntegrationService.Models.Generated.Company.IBusinessUnitDtoSingle(this.Context, GetPath("BusinessUnit"));
                }
                return this._BusinessUnit;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Sungero.IntegrationService.Models.Generated.Company.IBusinessUnitDtoSingle _BusinessUnit;
        /// <summary>
        /// There are no comments for RecipientLinks in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("RecipientLinks")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<global::Sungero.IntegrationService.Models.Generated.CoreEntities.IGroupRecipientLinksDto> RecipientLinks
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._RecipientLinks == null))
                {
                    this._RecipientLinks = Context.CreateQuery<global::Sungero.IntegrationService.Models.Generated.CoreEntities.IGroupRecipientLinksDto>(GetPath("RecipientLinks"));
                }
                return this._RecipientLinks;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::Sungero.IntegrationService.Models.Generated.CoreEntities.IGroupRecipientLinksDto> _RecipientLinks;
        /// <summary>
        /// There are no comments for Parent in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Parent")]
        public virtual global::Sungero.IntegrationService.Models.Generated.CoreEntities.IGroupDtoSingle Parent
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._Parent == null))
                {
                    this._Parent = new global::Sungero.IntegrationService.Models.Generated.CoreEntities.IGroupDtoSingle(this.Context, GetPath("Parent"));
                }
                return this._Parent;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Sungero.IntegrationService.Models.Generated.CoreEntities.IGroupDtoSingle _Parent;
    }
    /// <summary>
    /// There are no comments for IDepartmentDto in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("Id")]
    [global::Microsoft.OData.Client.OriginalNameAttribute("IDepartmentDto")]
    public partial class IDepartmentDto : global::Sungero.IntegrationService.Models.Generated.CoreEntities.IGroupDto
    {
        /// <summary>
        /// Create a new IDepartmentDto object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public static IDepartmentDto CreateIDepartmentDto(long ID)
        {
            IDepartmentDto iDepartmentDto = new IDepartmentDto();
            iDepartmentDto.Id = ID;
            return iDepartmentDto;
        }
        /// <summary>
        /// There are no comments for Property Phone in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("Phone")]
        public virtual string Phone
        {
            get
            {
                return this._Phone;
            }
            set
            {
                this.OnPhoneChanging(value);
                this._Phone = value;
                this.OnPhoneChanged();
                this.OnPropertyChanged("Phone");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _Phone;
        partial void OnPhoneChanging(string value);
        partial void OnPhoneChanged();
        /// <summary>
        /// There are no comments for Property ShortName in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("ShortName")]
        public virtual string ShortName
        {
            get
            {
                return this._ShortName;
            }
            set
            {
                this.OnShortNameChanging(value);
                this._ShortName = value;
                this.OnShortNameChanged();
                this.OnPropertyChanged("ShortName");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _ShortName;
        partial void OnShortNameChanging(string value);
        partial void OnShortNameChanged();
        /// <summary>
        /// There are no comments for Property Note in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("Note")]
        public virtual string Note
        {
            get
            {
                return this._Note;
            }
            set
            {
                this.OnNoteChanging(value);
                this._Note = value;
                this.OnNoteChanged();
                this.OnPropertyChanged("Note");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _Note;
        partial void OnNoteChanging(string value);
        partial void OnNoteChanged();
        /// <summary>
        /// There are no comments for Property Code in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("Code")]
        public virtual string Code
        {
            get
            {
                return this._Code;
            }
            set
            {
                this.OnCodeChanging(value);
                this._Code = value;
                this.OnCodeChanged();
                this.OnPropertyChanged("Code");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _Code;
        partial void OnCodeChanging(string value);
        partial void OnCodeChanged();
        /// <summary>
        /// There are no comments for Property ExternalId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("ExternalId")]
        public virtual string ExternalId
        {
            get
            {
                return this._ExternalId;
            }
            set
            {
                this.OnExternalIdChanging(value);
                this._ExternalId = value;
                this.OnExternalIdChanged();
                this.OnPropertyChanged("ExternalId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _ExternalId;
        partial void OnExternalIdChanging(string value);
        partial void OnExternalIdChanged();
        /// <summary>
        /// There are no comments for Property Manager in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("Manager")]
        public virtual global::Sungero.IntegrationService.Models.Generated.NewDreamSolution.IEmployeeDto Manager
        {
            get
            {
                return this._Manager;
            }
            set
            {
                this.OnManagerChanging(value);
                this._Manager = value;
                this.OnManagerChanged();
                this.OnPropertyChanged("Manager");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Sungero.IntegrationService.Models.Generated.NewDreamSolution.IEmployeeDto _Manager;
        partial void OnManagerChanging(global::Sungero.IntegrationService.Models.Generated.NewDreamSolution.IEmployeeDto value);
        partial void OnManagerChanged();
        /// <summary>
        /// There are no comments for Property HeadOffice in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("HeadOffice")]
        public virtual global::Sungero.IntegrationService.Models.Generated.Company.IDepartmentDto HeadOffice
        {
            get
            {
                return this._HeadOffice;
            }
            set
            {
                this.OnHeadOfficeChanging(value);
                this._HeadOffice = value;
                this.OnHeadOfficeChanged();
                this.OnPropertyChanged("HeadOffice");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Sungero.IntegrationService.Models.Generated.Company.IDepartmentDto _HeadOffice;
        partial void OnHeadOfficeChanging(global::Sungero.IntegrationService.Models.Generated.Company.IDepartmentDto value);
        partial void OnHeadOfficeChanged();
        /// <summary>
        /// There are no comments for Property BusinessUnit in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("BusinessUnit")]
        public virtual global::Sungero.IntegrationService.Models.Generated.Company.IBusinessUnitDto BusinessUnit
        {
            get
            {
                return this._BusinessUnit;
            }
            set
            {
                this.OnBusinessUnitChanging(value);
                this._BusinessUnit = value;
                this.OnBusinessUnitChanged();
                this.OnPropertyChanged("BusinessUnit");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Sungero.IntegrationService.Models.Generated.Company.IBusinessUnitDto _BusinessUnit;
        partial void OnBusinessUnitChanging(global::Sungero.IntegrationService.Models.Generated.Company.IBusinessUnitDto value);
        partial void OnBusinessUnitChanged();
    }
}
