//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generation date: 05.01.2024 23:02:18
namespace Sungero.IntegrationService.Models.Generated.EmployeeMutationsModule
{
    /// <summary>
    /// There are no comments for IEmployeeMutationsLogDtoSingle in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("IEmployeeMutationsLogDtoSingle")]
    public partial class IEmployeeMutationsLogDtoSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<IEmployeeMutationsLogDto>
    {
        /// <summary>
        /// Initialize a new IEmployeeMutationsLogDtoSingle object.
        /// </summary>
        public IEmployeeMutationsLogDtoSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new IEmployeeMutationsLogDtoSingle object.
        /// </summary>
        public IEmployeeMutationsLogDtoSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new IEmployeeMutationsLogDtoSingle object.
        /// </summary>
        public IEmployeeMutationsLogDtoSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<IEmployeeMutationsLogDto> query)
            : base(query) {}

        /// <summary>
        /// There are no comments for Employee in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Employee")]
        public virtual global::Sungero.IntegrationService.Models.Generated.NewDreamSolution.IEmployeeDtoSingle Employee
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._Employee == null))
                {
                    this._Employee = new global::Sungero.IntegrationService.Models.Generated.NewDreamSolution.IEmployeeDtoSingle(this.Context, GetPath("Employee"));
                }
                return this._Employee;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Sungero.IntegrationService.Models.Generated.NewDreamSolution.IEmployeeDtoSingle _Employee;
        /// <summary>
        /// There are no comments for Mutation in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Mutation")]
        public virtual global::Sungero.IntegrationService.Models.Generated.EmployeeMutationsModule.IEmployeeMutationKindDtoSingle Mutation
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._Mutation == null))
                {
                    this._Mutation = new global::Sungero.IntegrationService.Models.Generated.EmployeeMutationsModule.IEmployeeMutationKindDtoSingle(this.Context, GetPath("Mutation"));
                }
                return this._Mutation;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Sungero.IntegrationService.Models.Generated.EmployeeMutationsModule.IEmployeeMutationKindDtoSingle _Mutation;
    }
    /// <summary>
    /// There are no comments for IEmployeeMutationsLogDto in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("Id")]
    [global::Microsoft.OData.Client.OriginalNameAttribute("IEmployeeMutationsLogDto")]
    public partial class IEmployeeMutationsLogDto : global::Microsoft.OData.Client.BaseEntityType, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new IEmployeeMutationsLogDto object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public static IEmployeeMutationsLogDto CreateIEmployeeMutationsLogDto(long ID)
        {
            IEmployeeMutationsLogDto iEmployeeMutationsLogDto = new IEmployeeMutationsLogDto();
            iEmployeeMutationsLogDto.Id = ID;
            return iEmployeeMutationsLogDto;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("Id")]
        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "Id is required.")]
        public virtual long Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private long _Id;
        partial void OnIdChanging(long value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property AppliedDate in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("AppliedDate")]
        public virtual global::System.Nullable<global::System.DateTimeOffset> AppliedDate
        {
            get
            {
                return this._AppliedDate;
            }
            set
            {
                this.OnAppliedDateChanging(value);
                this._AppliedDate = value;
                this.OnAppliedDateChanged();
                this.OnPropertyChanged("AppliedDate");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::System.DateTimeOffset> _AppliedDate;
        partial void OnAppliedDateChanging(global::System.Nullable<global::System.DateTimeOffset> value);
        partial void OnAppliedDateChanged();
        /// <summary>
        /// There are no comments for Property Note in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("Note")]
        public virtual string Note
        {
            get
            {
                return this._Note;
            }
            set
            {
                this.OnNoteChanging(value);
                this._Note = value;
                this.OnNoteChanged();
                this.OnPropertyChanged("Note");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _Note;
        partial void OnNoteChanging(string value);
        partial void OnNoteChanged();
        /// <summary>
        /// There are no comments for Property Status in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("Status")]
        public virtual string Status
        {
            get
            {
                return this._Status;
            }
            set
            {
                this.OnStatusChanging(value);
                this._Status = value;
                this.OnStatusChanged();
                this.OnPropertyChanged("Status");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _Status;
        partial void OnStatusChanging(string value);
        partial void OnStatusChanged();
        /// <summary>
        /// There are no comments for Property Employee in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("Employee")]
        public virtual global::Sungero.IntegrationService.Models.Generated.NewDreamSolution.IEmployeeDto Employee
        {
            get
            {
                return this._Employee;
            }
            set
            {
                this.OnEmployeeChanging(value);
                this._Employee = value;
                this.OnEmployeeChanged();
                this.OnPropertyChanged("Employee");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Sungero.IntegrationService.Models.Generated.NewDreamSolution.IEmployeeDto _Employee;
        partial void OnEmployeeChanging(global::Sungero.IntegrationService.Models.Generated.NewDreamSolution.IEmployeeDto value);
        partial void OnEmployeeChanged();
        /// <summary>
        /// There are no comments for Property Mutation in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("Mutation")]
        public virtual global::Sungero.IntegrationService.Models.Generated.EmployeeMutationsModule.IEmployeeMutationKindDto Mutation
        {
            get
            {
                return this._Mutation;
            }
            set
            {
                this.OnMutationChanging(value);
                this._Mutation = value;
                this.OnMutationChanged();
                this.OnPropertyChanged("Mutation");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Sungero.IntegrationService.Models.Generated.EmployeeMutationsModule.IEmployeeMutationKindDto _Mutation;
        partial void OnMutationChanging(global::Sungero.IntegrationService.Models.Generated.EmployeeMutationsModule.IEmployeeMutationKindDto value);
        partial void OnMutationChanged();
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
}
