//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generation date: 05.01.2024 23:02:18
namespace Sungero.IntegrationService.Models.Generated.CoreEntities
{
    /// <summary>
    /// There are no comments for IGroupDtoSingle in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("IGroupDtoSingle")]
    public partial class IGroupDtoSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<IGroupDto>
    {
        /// <summary>
        /// Initialize a new IGroupDtoSingle object.
        /// </summary>
        public IGroupDtoSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new IGroupDtoSingle object.
        /// </summary>
        public IGroupDtoSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new IGroupDtoSingle object.
        /// </summary>
        public IGroupDtoSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<IGroupDto> query)
            : base(query) {}

        /// <summary>
        /// There are no comments for RecipientLinks in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("RecipientLinks")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<global::Sungero.IntegrationService.Models.Generated.CoreEntities.IGroupRecipientLinksDto> RecipientLinks
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._RecipientLinks == null))
                {
                    this._RecipientLinks = Context.CreateQuery<global::Sungero.IntegrationService.Models.Generated.CoreEntities.IGroupRecipientLinksDto>(GetPath("RecipientLinks"));
                }
                return this._RecipientLinks;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::Sungero.IntegrationService.Models.Generated.CoreEntities.IGroupRecipientLinksDto> _RecipientLinks;
        /// <summary>
        /// There are no comments for Parent in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Parent")]
        public virtual global::Sungero.IntegrationService.Models.Generated.CoreEntities.IGroupDtoSingle Parent
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._Parent == null))
                {
                    this._Parent = new global::Sungero.IntegrationService.Models.Generated.CoreEntities.IGroupDtoSingle(this.Context, GetPath("Parent"));
                }
                return this._Parent;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Sungero.IntegrationService.Models.Generated.CoreEntities.IGroupDtoSingle _Parent;
    }
    /// <summary>
    /// There are no comments for IGroupDto in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("Id")]
    [global::Microsoft.OData.Client.OriginalNameAttribute("IGroupDto")]
    public partial class IGroupDto : IRecipientDto
    {
        /// <summary>
        /// Create a new IGroupDto object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public static IGroupDto CreateIGroupDto(long ID)
        {
            IGroupDto iGroupDto = new IGroupDto();
            iGroupDto.Id = ID;
            return iGroupDto;
        }
        /// <summary>
        /// There are no comments for Property RecipientLinks in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("RecipientLinks")]
        public virtual global::Microsoft.OData.Client.DataServiceCollection<global::Sungero.IntegrationService.Models.Generated.CoreEntities.IGroupRecipientLinksDto> RecipientLinks
        {
            get
            {
                return this._RecipientLinks;
            }
            set
            {
                this.OnRecipientLinksChanging(value);
                this._RecipientLinks = value;
                this.OnRecipientLinksChanged();
                this.OnPropertyChanged("RecipientLinks");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceCollection<global::Sungero.IntegrationService.Models.Generated.CoreEntities.IGroupRecipientLinksDto> _RecipientLinks = new global::Microsoft.OData.Client.DataServiceCollection<global::Sungero.IntegrationService.Models.Generated.CoreEntities.IGroupRecipientLinksDto>(null, global::Microsoft.OData.Client.TrackingMode.None);
        partial void OnRecipientLinksChanging(global::Microsoft.OData.Client.DataServiceCollection<global::Sungero.IntegrationService.Models.Generated.CoreEntities.IGroupRecipientLinksDto> value);
        partial void OnRecipientLinksChanged();
        /// <summary>
        /// There are no comments for Property Parent in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("Parent")]
        public virtual global::Sungero.IntegrationService.Models.Generated.CoreEntities.IGroupDto Parent
        {
            get
            {
                return this._Parent;
            }
            set
            {
                this.OnParentChanging(value);
                this._Parent = value;
                this.OnParentChanged();
                this.OnPropertyChanged("Parent");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Sungero.IntegrationService.Models.Generated.CoreEntities.IGroupDto _Parent;
        partial void OnParentChanging(global::Sungero.IntegrationService.Models.Generated.CoreEntities.IGroupDto value);
        partial void OnParentChanged();
    }
}
