//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generation date: 26.11.2023 2:59:27
namespace Sungero.IntegrationService.Models.Generated.CoreEntities
{
    /// <summary>
    /// There are no comments for IGroupRecipientLinksDtoSingle in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("IGroupRecipientLinksDtoSingle")]
    public partial class IGroupRecipientLinksDtoSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<IGroupRecipientLinksDto>
    {
        /// <summary>
        /// Initialize a new IGroupRecipientLinksDtoSingle object.
        /// </summary>
        public IGroupRecipientLinksDtoSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new IGroupRecipientLinksDtoSingle object.
        /// </summary>
        public IGroupRecipientLinksDtoSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new IGroupRecipientLinksDtoSingle object.
        /// </summary>
        public IGroupRecipientLinksDtoSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<IGroupRecipientLinksDto> query)
            : base(query) {}

        /// <summary>
        /// There are no comments for Group in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Group")]
        public virtual global::Sungero.IntegrationService.Models.Generated.CoreEntities.IGroupDtoSingle Group
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._Group == null))
                {
                    this._Group = new global::Sungero.IntegrationService.Models.Generated.CoreEntities.IGroupDtoSingle(this.Context, GetPath("Group"));
                }
                return this._Group;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Sungero.IntegrationService.Models.Generated.CoreEntities.IGroupDtoSingle _Group;
        /// <summary>
        /// There are no comments for Member in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Member")]
        public virtual global::Sungero.IntegrationService.Models.Generated.CoreEntities.IRecipientDtoSingle Member
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._Member == null))
                {
                    this._Member = new global::Sungero.IntegrationService.Models.Generated.CoreEntities.IRecipientDtoSingle(this.Context, GetPath("Member"));
                }
                return this._Member;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Sungero.IntegrationService.Models.Generated.CoreEntities.IRecipientDtoSingle _Member;
    }
    /// <summary>
    /// There are no comments for IGroupRecipientLinksDto in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("Id")]
    [global::Microsoft.OData.Client.OriginalNameAttribute("IGroupRecipientLinksDto")]
    public partial class IGroupRecipientLinksDto : global::Microsoft.OData.Client.BaseEntityType, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new IGroupRecipientLinksDto object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public static IGroupRecipientLinksDto CreateIGroupRecipientLinksDto(long ID)
        {
            IGroupRecipientLinksDto iGroupRecipientLinksDto = new IGroupRecipientLinksDto();
            iGroupRecipientLinksDto.Id = ID;
            return iGroupRecipientLinksDto;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("Id")]
        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "Id is required.")]
        public virtual long Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private long _Id;
        partial void OnIdChanging(long value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Sid in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("Sid")]
        public virtual global::System.Nullable<global::System.Guid> Sid
        {
            get
            {
                return this._Sid;
            }
            set
            {
                this.OnSidChanging(value);
                this._Sid = value;
                this.OnSidChanged();
                this.OnPropertyChanged("Sid");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::System.Guid> _Sid;
        partial void OnSidChanging(global::System.Nullable<global::System.Guid> value);
        partial void OnSidChanged();
        /// <summary>
        /// There are no comments for Property Group in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("Group")]
        public virtual global::Sungero.IntegrationService.Models.Generated.CoreEntities.IGroupDto Group
        {
            get
            {
                return this._Group;
            }
            set
            {
                this.OnGroupChanging(value);
                this._Group = value;
                this.OnGroupChanged();
                this.OnPropertyChanged("Group");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Sungero.IntegrationService.Models.Generated.CoreEntities.IGroupDto _Group;
        partial void OnGroupChanging(global::Sungero.IntegrationService.Models.Generated.CoreEntities.IGroupDto value);
        partial void OnGroupChanged();
        /// <summary>
        /// There are no comments for Property Member in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("Member")]
        public virtual global::Sungero.IntegrationService.Models.Generated.CoreEntities.IRecipientDto Member
        {
            get
            {
                return this._Member;
            }
            set
            {
                this.OnMemberChanging(value);
                this._Member = value;
                this.OnMemberChanged();
                this.OnPropertyChanged("Member");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Sungero.IntegrationService.Models.Generated.CoreEntities.IRecipientDto _Member;
        partial void OnMemberChanging(global::Sungero.IntegrationService.Models.Generated.CoreEntities.IRecipientDto value);
        partial void OnMemberChanged();
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
}
