//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generation date: 26.11.2023 2:59:27
namespace Sungero.IntegrationService.Models.Generated.CoreEntities
{
    /// <summary>
    /// There are no comments for ILoginDtoSingle in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("ILoginDtoSingle")]
    public partial class ILoginDtoSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<ILoginDto>
    {
        /// <summary>
        /// Initialize a new ILoginDtoSingle object.
        /// </summary>
        public ILoginDtoSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new ILoginDtoSingle object.
        /// </summary>
        public ILoginDtoSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new ILoginDtoSingle object.
        /// </summary>
        public ILoginDtoSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<ILoginDto> query)
            : base(query) {}

    }
    /// <summary>
    /// There are no comments for ILoginDto in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("Id")]
    [global::Microsoft.OData.Client.OriginalNameAttribute("ILoginDto")]
    public partial class ILoginDto : global::Microsoft.OData.Client.BaseEntityType, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new ILoginDto object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public static ILoginDto CreateILoginDto(long ID)
        {
            ILoginDto iLoginDto = new ILoginDto();
            iLoginDto.Id = ID;
            return iLoginDto;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("Id")]
        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "Id is required.")]
        public virtual long Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private long _Id;
        partial void OnIdChanging(long value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property NeedChangePassword in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("NeedChangePassword")]
        public virtual global::System.Nullable<bool> NeedChangePassword
        {
            get
            {
                return this._NeedChangePassword;
            }
            set
            {
                this.OnNeedChangePasswordChanging(value);
                this._NeedChangePassword = value;
                this.OnNeedChangePasswordChanged();
                this.OnPropertyChanged("NeedChangePassword");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<bool> _NeedChangePassword;
        partial void OnNeedChangePasswordChanging(global::System.Nullable<bool> value);
        partial void OnNeedChangePasswordChanged();
        /// <summary>
        /// There are no comments for Property LoginName in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("LoginName")]
        public virtual string LoginName
        {
            get
            {
                return this._LoginName;
            }
            set
            {
                this.OnLoginNameChanging(value);
                this._LoginName = value;
                this.OnLoginNameChanged();
                this.OnPropertyChanged("LoginName");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _LoginName;
        partial void OnLoginNameChanging(string value);
        partial void OnLoginNameChanged();
        /// <summary>
        /// There are no comments for Property TypeAuthentication in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("TypeAuthentication")]
        public virtual string TypeAuthentication
        {
            get
            {
                return this._TypeAuthentication;
            }
            set
            {
                this.OnTypeAuthenticationChanging(value);
                this._TypeAuthentication = value;
                this.OnTypeAuthenticationChanged();
                this.OnPropertyChanged("TypeAuthentication");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _TypeAuthentication;
        partial void OnTypeAuthenticationChanging(string value);
        partial void OnTypeAuthenticationChanged();
        /// <summary>
        /// There are no comments for Property Status in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("Status")]
        public virtual string Status
        {
            get
            {
                return this._Status;
            }
            set
            {
                this.OnStatusChanging(value);
                this._Status = value;
                this.OnStatusChanged();
                this.OnPropertyChanged("Status");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _Status;
        partial void OnStatusChanging(string value);
        partial void OnStatusChanged();
        /// <summary>
        /// There are no comments for Property PasswordLastChangeDate in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("PasswordLastChangeDate")]
        public virtual global::System.Nullable<global::System.DateTimeOffset> PasswordLastChangeDate
        {
            get
            {
                return this._PasswordLastChangeDate;
            }
            set
            {
                this.OnPasswordLastChangeDateChanging(value);
                this._PasswordLastChangeDate = value;
                this.OnPasswordLastChangeDateChanged();
                this.OnPropertyChanged("PasswordLastChangeDate");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::System.DateTimeOffset> _PasswordLastChangeDate;
        partial void OnPasswordLastChangeDateChanging(global::System.Nullable<global::System.DateTimeOffset> value);
        partial void OnPasswordLastChangeDateChanged();
        /// <summary>
        /// There are no comments for Property LockoutEndDate in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("LockoutEndDate")]
        public virtual global::System.Nullable<global::System.DateTimeOffset> LockoutEndDate
        {
            get
            {
                return this._LockoutEndDate;
            }
            set
            {
                this.OnLockoutEndDateChanging(value);
                this._LockoutEndDate = value;
                this.OnLockoutEndDateChanged();
                this.OnPropertyChanged("LockoutEndDate");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::System.DateTimeOffset> _LockoutEndDate;
        partial void OnLockoutEndDateChanging(global::System.Nullable<global::System.DateTimeOffset> value);
        partial void OnLockoutEndDateChanged();
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
}
