//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generation date: 05.01.2024 23:02:18
namespace Sungero.IntegrationService.Models.Generated.Meetings
{
    /// <summary>
    /// There are no comments for IMeetingMembersDtoSingle in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("IMeetingMembersDtoSingle")]
    public partial class IMeetingMembersDtoSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<IMeetingMembersDto>
    {
        /// <summary>
        /// Initialize a new IMeetingMembersDtoSingle object.
        /// </summary>
        public IMeetingMembersDtoSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new IMeetingMembersDtoSingle object.
        /// </summary>
        public IMeetingMembersDtoSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new IMeetingMembersDtoSingle object.
        /// </summary>
        public IMeetingMembersDtoSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<IMeetingMembersDto> query)
            : base(query) {}

        /// <summary>
        /// There are no comments for Meeting in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Meeting")]
        public virtual global::Sungero.IntegrationService.Models.Generated.Meetings.IMeetingDtoSingle Meeting
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._Meeting == null))
                {
                    this._Meeting = new global::Sungero.IntegrationService.Models.Generated.Meetings.IMeetingDtoSingle(this.Context, GetPath("Meeting"));
                }
                return this._Meeting;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Sungero.IntegrationService.Models.Generated.Meetings.IMeetingDtoSingle _Meeting;
        /// <summary>
        /// There are no comments for Member in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Member")]
        public virtual global::Sungero.IntegrationService.Models.Generated.CoreEntities.IRecipientDtoSingle Member
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._Member == null))
                {
                    this._Member = new global::Sungero.IntegrationService.Models.Generated.CoreEntities.IRecipientDtoSingle(this.Context, GetPath("Member"));
                }
                return this._Member;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Sungero.IntegrationService.Models.Generated.CoreEntities.IRecipientDtoSingle _Member;
    }
    /// <summary>
    /// There are no comments for IMeetingMembersDto in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("Id")]
    [global::Microsoft.OData.Client.OriginalNameAttribute("IMeetingMembersDto")]
    public partial class IMeetingMembersDto : global::Microsoft.OData.Client.BaseEntityType, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new IMeetingMembersDto object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public static IMeetingMembersDto CreateIMeetingMembersDto(long ID)
        {
            IMeetingMembersDto iMeetingMembersDto = new IMeetingMembersDto();
            iMeetingMembersDto.Id = ID;
            return iMeetingMembersDto;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("Id")]
        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "Id is required.")]
        public virtual long Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private long _Id;
        partial void OnIdChanging(long value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Meeting in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("Meeting")]
        public virtual global::Sungero.IntegrationService.Models.Generated.Meetings.IMeetingDto Meeting
        {
            get
            {
                return this._Meeting;
            }
            set
            {
                this.OnMeetingChanging(value);
                this._Meeting = value;
                this.OnMeetingChanged();
                this.OnPropertyChanged("Meeting");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Sungero.IntegrationService.Models.Generated.Meetings.IMeetingDto _Meeting;
        partial void OnMeetingChanging(global::Sungero.IntegrationService.Models.Generated.Meetings.IMeetingDto value);
        partial void OnMeetingChanged();
        /// <summary>
        /// There are no comments for Property Member in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("Member")]
        public virtual global::Sungero.IntegrationService.Models.Generated.CoreEntities.IRecipientDto Member
        {
            get
            {
                return this._Member;
            }
            set
            {
                this.OnMemberChanging(value);
                this._Member = value;
                this.OnMemberChanged();
                this.OnPropertyChanged("Member");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Sungero.IntegrationService.Models.Generated.CoreEntities.IRecipientDto _Member;
        partial void OnMemberChanging(global::Sungero.IntegrationService.Models.Generated.CoreEntities.IRecipientDto value);
        partial void OnMemberChanged();
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
}
