//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generation date: 26.11.2023 2:59:27
namespace Sungero.IntegrationService.Models.Generated.Content
{
}
namespace Sungero.IntegrationService.Models.Generated.Docflow
{
}
namespace Sungero.IntegrationService.Models.Generated.Contracts
{
}
namespace Sungero.IntegrationService.Models.Generated.FinancialArchive
{
}
namespace Sungero.IntegrationService.Models.Generated.RecordManagement
{
}
namespace Sungero.IntegrationService.Models.Generated.Meetings
{
}
namespace Sungero.IntegrationService.Models.Generated.Projects
{
}
namespace Sungero.IntegrationService.Models.Generated.CoreEntities
{
}
namespace Sungero.IntegrationService.Models.Generated.Workflow
{
}
namespace Sungero.IntegrationService.Models.Generated.Company
{
}
namespace Sungero.IntegrationService.Models.Generated.DreamSolution
{
}
namespace Sungero.IntegrationService.Models.Generated.EmployeeModule
{
}
namespace Sungero.IntegrationService.Models.Generated.HelpDesk
{
}
namespace Sungero.IntegrationService.Models.Generated.Commons
{
}
namespace Sungero.IntegrationService.Models.Generated.Exchange
{
}
namespace Sungero.IntegrationService.Models.Generated.ExchangeCore
{
}
namespace Sungero.IntegrationService.Models.Generated.Parties
{
}
namespace Sungero.IntegrationService.Models.Generated.PowerOfAttorneyCore
{
}
namespace Sungero.IntegrationService.Models.Generated.SmartProcessing
{
}
namespace Sungero.IntegrationService.Models.Generated.Content.Interfaces
{
}
namespace Sungero.IntegrationService.Controllers.Generated
{
}
namespace Sungero.IntegrationService.Generator
{
}
namespace SmartProcessing
{
}
namespace Shell
{
}
namespace RecordManagement
{
}
namespace Projects
{
}
namespace Parties
{
}
namespace Exchange
{
}
namespace ExchangeCore
{
}
namespace Docflow
{
}
namespace Company
{
}
namespace Content
{
}
namespace CoreEntities
{
}
namespace Sungero.IntegrationService
{
    /// <summary>
    /// There are no comments for Container in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("Container")]
    public partial class Container : global::Microsoft.OData.Client.DataServiceContext
    {
        /// <summary>
        /// Initialize a new Container object.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public Container(global::System.Uri serviceRoot) :
                this(serviceRoot, global::Microsoft.OData.Client.ODataProtocolVersion.V4)
        {
        }

        /// <summary>
        /// Initialize a new Container object.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public Container(global::System.Uri serviceRoot, global::Microsoft.OData.Client.ODataProtocolVersion protocolVersion) :
                base(serviceRoot, protocolVersion)
        {
            this.ResolveName = new global::System.Func<global::System.Type, string>(this.ResolveNameFromType);
            this.ResolveType = new global::System.Func<string, global::System.Type>(this.ResolveTypeFromName);
            this.OnContextCreated();
            this.Format.LoadServiceModel = GeneratedEdmModel.GetInstance;
            this.Format.UseJson();
        }
        partial void OnContextCreated();
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        protected global::System.Type ResolveTypeFromName(string typeName)
        {
            global::System.Type resolvedType = this.DefaultResolveType(typeName, "Sungero.IntegrationService.Models.Generated.PowerOfAttorneyCore", "Sungero.IntegrationService.Models.Generated.PowerOfAttorneyCore");
            if ((resolvedType != null))
            {
                return resolvedType;
            }
            resolvedType = this.DefaultResolveType(typeName, "Sungero.IntegrationService.Models.Generated.Content.Interfaces", "Sungero.IntegrationService.Models.Generated.Content.Interfaces");
            if ((resolvedType != null))
            {
                return resolvedType;
            }
            resolvedType = this.DefaultResolveType(typeName, "Sungero.IntegrationService.Models.Generated.FinancialArchive", "Sungero.IntegrationService.Models.Generated.FinancialArchive");
            if ((resolvedType != null))
            {
                return resolvedType;
            }
            resolvedType = this.DefaultResolveType(typeName, "Sungero.IntegrationService.Models.Generated.RecordManagement", "Sungero.IntegrationService.Models.Generated.RecordManagement");
            if ((resolvedType != null))
            {
                return resolvedType;
            }
            resolvedType = this.DefaultResolveType(typeName, "Sungero.IntegrationService.Models.Generated.SmartProcessing", "Sungero.IntegrationService.Models.Generated.SmartProcessing");
            if ((resolvedType != null))
            {
                return resolvedType;
            }
            resolvedType = this.DefaultResolveType(typeName, "Sungero.IntegrationService.Models.Generated.EmployeeModule", "Sungero.IntegrationService.Models.Generated.EmployeeModule");
            if ((resolvedType != null))
            {
                return resolvedType;
            }
            resolvedType = this.DefaultResolveType(typeName, "Sungero.IntegrationService.Models.Generated.DreamSolution", "Sungero.IntegrationService.Models.Generated.DreamSolution");
            if ((resolvedType != null))
            {
                return resolvedType;
            }
            resolvedType = this.DefaultResolveType(typeName, "Sungero.IntegrationService.Models.Generated.CoreEntities", "Sungero.IntegrationService.Models.Generated.CoreEntities");
            if ((resolvedType != null))
            {
                return resolvedType;
            }
            resolvedType = this.DefaultResolveType(typeName, "Sungero.IntegrationService.Models.Generated.ExchangeCore", "Sungero.IntegrationService.Models.Generated.ExchangeCore");
            if ((resolvedType != null))
            {
                return resolvedType;
            }
            resolvedType = this.DefaultResolveType(typeName, "Sungero.IntegrationService.Models.Generated.Contracts", "Sungero.IntegrationService.Models.Generated.Contracts");
            if ((resolvedType != null))
            {
                return resolvedType;
            }
            resolvedType = this.DefaultResolveType(typeName, "Sungero.IntegrationService.Models.Generated.Exchange", "Sungero.IntegrationService.Models.Generated.Exchange");
            if ((resolvedType != null))
            {
                return resolvedType;
            }
            resolvedType = this.DefaultResolveType(typeName, "Sungero.IntegrationService.Models.Generated.HelpDesk", "Sungero.IntegrationService.Models.Generated.HelpDesk");
            if ((resolvedType != null))
            {
                return resolvedType;
            }
            resolvedType = this.DefaultResolveType(typeName, "Sungero.IntegrationService.Models.Generated.Meetings", "Sungero.IntegrationService.Models.Generated.Meetings");
            if ((resolvedType != null))
            {
                return resolvedType;
            }
            resolvedType = this.DefaultResolveType(typeName, "Sungero.IntegrationService.Models.Generated.Projects", "Sungero.IntegrationService.Models.Generated.Projects");
            if ((resolvedType != null))
            {
                return resolvedType;
            }
            resolvedType = this.DefaultResolveType(typeName, "Sungero.IntegrationService.Models.Generated.Workflow", "Sungero.IntegrationService.Models.Generated.Workflow");
            if ((resolvedType != null))
            {
                return resolvedType;
            }
            resolvedType = this.DefaultResolveType(typeName, "Sungero.IntegrationService.Models.Generated.Commons", "Sungero.IntegrationService.Models.Generated.Commons");
            if ((resolvedType != null))
            {
                return resolvedType;
            }
            resolvedType = this.DefaultResolveType(typeName, "Sungero.IntegrationService.Models.Generated.Company", "Sungero.IntegrationService.Models.Generated.Company");
            if ((resolvedType != null))
            {
                return resolvedType;
            }
            resolvedType = this.DefaultResolveType(typeName, "Sungero.IntegrationService.Models.Generated.Content", "Sungero.IntegrationService.Models.Generated.Content");
            if ((resolvedType != null))
            {
                return resolvedType;
            }
            resolvedType = this.DefaultResolveType(typeName, "Sungero.IntegrationService.Models.Generated.Docflow", "Sungero.IntegrationService.Models.Generated.Docflow");
            if ((resolvedType != null))
            {
                return resolvedType;
            }
            resolvedType = this.DefaultResolveType(typeName, "Sungero.IntegrationService.Models.Generated.Parties", "Sungero.IntegrationService.Models.Generated.Parties");
            if ((resolvedType != null))
            {
                return resolvedType;
            }
            resolvedType = this.DefaultResolveType(typeName, "Sungero.IntegrationService.Controllers.Generated", "Sungero.IntegrationService.Controllers.Generated");
            if ((resolvedType != null))
            {
                return resolvedType;
            }
            resolvedType = this.DefaultResolveType(typeName, "Sungero.IntegrationService.Generator", "Sungero.IntegrationService.Generator");
            if ((resolvedType != null))
            {
                return resolvedType;
            }
            resolvedType = this.DefaultResolveType(typeName, "Sungero.IntegrationService", "Sungero.IntegrationService");
            if ((resolvedType != null))
            {
                return resolvedType;
            }
            resolvedType = this.DefaultResolveType(typeName, "RecordManagement", "RecordManagement");
            if ((resolvedType != null))
            {
                return resolvedType;
            }
            resolvedType = this.DefaultResolveType(typeName, "SmartProcessing", "SmartProcessing");
            if ((resolvedType != null))
            {
                return resolvedType;
            }
            resolvedType = this.DefaultResolveType(typeName, "CoreEntities", "CoreEntities");
            if ((resolvedType != null))
            {
                return resolvedType;
            }
            resolvedType = this.DefaultResolveType(typeName, "ExchangeCore", "ExchangeCore");
            if ((resolvedType != null))
            {
                return resolvedType;
            }
            resolvedType = this.DefaultResolveType(typeName, "Exchange", "Exchange");
            if ((resolvedType != null))
            {
                return resolvedType;
            }
            resolvedType = this.DefaultResolveType(typeName, "Projects", "Projects");
            if ((resolvedType != null))
            {
                return resolvedType;
            }
            resolvedType = this.DefaultResolveType(typeName, "Company", "Company");
            if ((resolvedType != null))
            {
                return resolvedType;
            }
            resolvedType = this.DefaultResolveType(typeName, "Content", "Content");
            if ((resolvedType != null))
            {
                return resolvedType;
            }
            resolvedType = this.DefaultResolveType(typeName, "Docflow", "Docflow");
            if ((resolvedType != null))
            {
                return resolvedType;
            }
            resolvedType = this.DefaultResolveType(typeName, "Parties", "Parties");
            if ((resolvedType != null))
            {
                return resolvedType;
            }
            resolvedType = this.DefaultResolveType(typeName, "Shell", "Shell");
            if ((resolvedType != null))
            {
                return resolvedType;
            }
            return null;
        }
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        protected string ResolveNameFromType(global::System.Type clientType)
        {
            global::Microsoft.OData.Client.OriginalNameAttribute originalNameAttribute = (global::Microsoft.OData.Client.OriginalNameAttribute)global::System.Linq.Enumerable.SingleOrDefault(global::Microsoft.OData.Client.Utility.GetCustomAttributes(clientType, typeof(global::Microsoft.OData.Client.OriginalNameAttribute), true));
            if (clientType.Namespace.Equals("Sungero.IntegrationService.Models.Generated.PowerOfAttorneyCore", global::System.StringComparison.Ordinal))
            {
                if (originalNameAttribute != null)
                {
                    return string.Concat("Sungero.IntegrationService.Models.Generated.PowerOfAttorneyCore.", originalNameAttribute.OriginalName);
                }
                return string.Concat("Sungero.IntegrationService.Models.Generated.PowerOfAttorneyCore.", clientType.Name);
            }
            if (clientType.Namespace.Equals("Sungero.IntegrationService.Models.Generated.Content.Interfaces", global::System.StringComparison.Ordinal))
            {
                if (originalNameAttribute != null)
                {
                    return string.Concat("Sungero.IntegrationService.Models.Generated.Content.Interfaces.", originalNameAttribute.OriginalName);
                }
                return string.Concat("Sungero.IntegrationService.Models.Generated.Content.Interfaces.", clientType.Name);
            }
            if (clientType.Namespace.Equals("Sungero.IntegrationService.Models.Generated.FinancialArchive", global::System.StringComparison.Ordinal))
            {
                if (originalNameAttribute != null)
                {
                    return string.Concat("Sungero.IntegrationService.Models.Generated.FinancialArchive.", originalNameAttribute.OriginalName);
                }
                return string.Concat("Sungero.IntegrationService.Models.Generated.FinancialArchive.", clientType.Name);
            }
            if (clientType.Namespace.Equals("Sungero.IntegrationService.Models.Generated.RecordManagement", global::System.StringComparison.Ordinal))
            {
                if (originalNameAttribute != null)
                {
                    return string.Concat("Sungero.IntegrationService.Models.Generated.RecordManagement.", originalNameAttribute.OriginalName);
                }
                return string.Concat("Sungero.IntegrationService.Models.Generated.RecordManagement.", clientType.Name);
            }
            if (clientType.Namespace.Equals("Sungero.IntegrationService.Models.Generated.SmartProcessing", global::System.StringComparison.Ordinal))
            {
                if (originalNameAttribute != null)
                {
                    return string.Concat("Sungero.IntegrationService.Models.Generated.SmartProcessing.", originalNameAttribute.OriginalName);
                }
                return string.Concat("Sungero.IntegrationService.Models.Generated.SmartProcessing.", clientType.Name);
            }
            if (clientType.Namespace.Equals("Sungero.IntegrationService.Models.Generated.EmployeeModule", global::System.StringComparison.Ordinal))
            {
                if (originalNameAttribute != null)
                {
                    return string.Concat("Sungero.IntegrationService.Models.Generated.EmployeeModule.", originalNameAttribute.OriginalName);
                }
                return string.Concat("Sungero.IntegrationService.Models.Generated.EmployeeModule.", clientType.Name);
            }
            if (clientType.Namespace.Equals("Sungero.IntegrationService.Models.Generated.DreamSolution", global::System.StringComparison.Ordinal))
            {
                if (originalNameAttribute != null)
                {
                    return string.Concat("Sungero.IntegrationService.Models.Generated.DreamSolution.", originalNameAttribute.OriginalName);
                }
                return string.Concat("Sungero.IntegrationService.Models.Generated.DreamSolution.", clientType.Name);
            }
            if (clientType.Namespace.Equals("Sungero.IntegrationService.Models.Generated.CoreEntities", global::System.StringComparison.Ordinal))
            {
                if (originalNameAttribute != null)
                {
                    return string.Concat("Sungero.IntegrationService.Models.Generated.CoreEntities.", originalNameAttribute.OriginalName);
                }
                return string.Concat("Sungero.IntegrationService.Models.Generated.CoreEntities.", clientType.Name);
            }
            if (clientType.Namespace.Equals("Sungero.IntegrationService.Models.Generated.ExchangeCore", global::System.StringComparison.Ordinal))
            {
                if (originalNameAttribute != null)
                {
                    return string.Concat("Sungero.IntegrationService.Models.Generated.ExchangeCore.", originalNameAttribute.OriginalName);
                }
                return string.Concat("Sungero.IntegrationService.Models.Generated.ExchangeCore.", clientType.Name);
            }
            if (clientType.Namespace.Equals("Sungero.IntegrationService.Models.Generated.Contracts", global::System.StringComparison.Ordinal))
            {
                if (originalNameAttribute != null)
                {
                    return string.Concat("Sungero.IntegrationService.Models.Generated.Contracts.", originalNameAttribute.OriginalName);
                }
                return string.Concat("Sungero.IntegrationService.Models.Generated.Contracts.", clientType.Name);
            }
            if (clientType.Namespace.Equals("Sungero.IntegrationService.Models.Generated.Exchange", global::System.StringComparison.Ordinal))
            {
                if (originalNameAttribute != null)
                {
                    return string.Concat("Sungero.IntegrationService.Models.Generated.Exchange.", originalNameAttribute.OriginalName);
                }
                return string.Concat("Sungero.IntegrationService.Models.Generated.Exchange.", clientType.Name);
            }
            if (clientType.Namespace.Equals("Sungero.IntegrationService.Models.Generated.HelpDesk", global::System.StringComparison.Ordinal))
            {
                if (originalNameAttribute != null)
                {
                    return string.Concat("Sungero.IntegrationService.Models.Generated.HelpDesk.", originalNameAttribute.OriginalName);
                }
                return string.Concat("Sungero.IntegrationService.Models.Generated.HelpDesk.", clientType.Name);
            }
            if (clientType.Namespace.Equals("Sungero.IntegrationService.Models.Generated.Meetings", global::System.StringComparison.Ordinal))
            {
                if (originalNameAttribute != null)
                {
                    return string.Concat("Sungero.IntegrationService.Models.Generated.Meetings.", originalNameAttribute.OriginalName);
                }
                return string.Concat("Sungero.IntegrationService.Models.Generated.Meetings.", clientType.Name);
            }
            if (clientType.Namespace.Equals("Sungero.IntegrationService.Models.Generated.Projects", global::System.StringComparison.Ordinal))
            {
                if (originalNameAttribute != null)
                {
                    return string.Concat("Sungero.IntegrationService.Models.Generated.Projects.", originalNameAttribute.OriginalName);
                }
                return string.Concat("Sungero.IntegrationService.Models.Generated.Projects.", clientType.Name);
            }
            if (clientType.Namespace.Equals("Sungero.IntegrationService.Models.Generated.Workflow", global::System.StringComparison.Ordinal))
            {
                if (originalNameAttribute != null)
                {
                    return string.Concat("Sungero.IntegrationService.Models.Generated.Workflow.", originalNameAttribute.OriginalName);
                }
                return string.Concat("Sungero.IntegrationService.Models.Generated.Workflow.", clientType.Name);
            }
            if (clientType.Namespace.Equals("Sungero.IntegrationService.Models.Generated.Commons", global::System.StringComparison.Ordinal))
            {
                if (originalNameAttribute != null)
                {
                    return string.Concat("Sungero.IntegrationService.Models.Generated.Commons.", originalNameAttribute.OriginalName);
                }
                return string.Concat("Sungero.IntegrationService.Models.Generated.Commons.", clientType.Name);
            }
            if (clientType.Namespace.Equals("Sungero.IntegrationService.Models.Generated.Company", global::System.StringComparison.Ordinal))
            {
                if (originalNameAttribute != null)
                {
                    return string.Concat("Sungero.IntegrationService.Models.Generated.Company.", originalNameAttribute.OriginalName);
                }
                return string.Concat("Sungero.IntegrationService.Models.Generated.Company.", clientType.Name);
            }
            if (clientType.Namespace.Equals("Sungero.IntegrationService.Models.Generated.Content", global::System.StringComparison.Ordinal))
            {
                if (originalNameAttribute != null)
                {
                    return string.Concat("Sungero.IntegrationService.Models.Generated.Content.", originalNameAttribute.OriginalName);
                }
                return string.Concat("Sungero.IntegrationService.Models.Generated.Content.", clientType.Name);
            }
            if (clientType.Namespace.Equals("Sungero.IntegrationService.Models.Generated.Docflow", global::System.StringComparison.Ordinal))
            {
                if (originalNameAttribute != null)
                {
                    return string.Concat("Sungero.IntegrationService.Models.Generated.Docflow.", originalNameAttribute.OriginalName);
                }
                return string.Concat("Sungero.IntegrationService.Models.Generated.Docflow.", clientType.Name);
            }
            if (clientType.Namespace.Equals("Sungero.IntegrationService.Models.Generated.Parties", global::System.StringComparison.Ordinal))
            {
                if (originalNameAttribute != null)
                {
                    return string.Concat("Sungero.IntegrationService.Models.Generated.Parties.", originalNameAttribute.OriginalName);
                }
                return string.Concat("Sungero.IntegrationService.Models.Generated.Parties.", clientType.Name);
            }
            if (clientType.Namespace.Equals("Sungero.IntegrationService.Controllers.Generated", global::System.StringComparison.Ordinal))
            {
                if (originalNameAttribute != null)
                {
                    return string.Concat("Sungero.IntegrationService.Controllers.Generated.", originalNameAttribute.OriginalName);
                }
                return string.Concat("Sungero.IntegrationService.Controllers.Generated.", clientType.Name);
            }
            if (clientType.Namespace.Equals("Sungero.IntegrationService.Generator", global::System.StringComparison.Ordinal))
            {
                if (originalNameAttribute != null)
                {
                    return string.Concat("Sungero.IntegrationService.Generator.", originalNameAttribute.OriginalName);
                }
                return string.Concat("Sungero.IntegrationService.Generator.", clientType.Name);
            }
            if (clientType.Namespace.Equals("Sungero.IntegrationService", global::System.StringComparison.Ordinal))
            {
                if (originalNameAttribute != null)
                {
                    return string.Concat("Sungero.IntegrationService.", originalNameAttribute.OriginalName);
                }
                return string.Concat("Sungero.IntegrationService.", clientType.Name);
            }
            if (clientType.Namespace.Equals("RecordManagement", global::System.StringComparison.Ordinal))
            {
                if (originalNameAttribute != null)
                {
                    return string.Concat("RecordManagement.", originalNameAttribute.OriginalName);
                }
                return string.Concat("RecordManagement.", clientType.Name);
            }
            if (clientType.Namespace.Equals("SmartProcessing", global::System.StringComparison.Ordinal))
            {
                if (originalNameAttribute != null)
                {
                    return string.Concat("SmartProcessing.", originalNameAttribute.OriginalName);
                }
                return string.Concat("SmartProcessing.", clientType.Name);
            }
            if (clientType.Namespace.Equals("CoreEntities", global::System.StringComparison.Ordinal))
            {
                if (originalNameAttribute != null)
                {
                    return string.Concat("CoreEntities.", originalNameAttribute.OriginalName);
                }
                return string.Concat("CoreEntities.", clientType.Name);
            }
            if (clientType.Namespace.Equals("ExchangeCore", global::System.StringComparison.Ordinal))
            {
                if (originalNameAttribute != null)
                {
                    return string.Concat("ExchangeCore.", originalNameAttribute.OriginalName);
                }
                return string.Concat("ExchangeCore.", clientType.Name);
            }
            if (clientType.Namespace.Equals("Exchange", global::System.StringComparison.Ordinal))
            {
                if (originalNameAttribute != null)
                {
                    return string.Concat("Exchange.", originalNameAttribute.OriginalName);
                }
                return string.Concat("Exchange.", clientType.Name);
            }
            if (clientType.Namespace.Equals("Projects", global::System.StringComparison.Ordinal))
            {
                if (originalNameAttribute != null)
                {
                    return string.Concat("Projects.", originalNameAttribute.OriginalName);
                }
                return string.Concat("Projects.", clientType.Name);
            }
            if (clientType.Namespace.Equals("Company", global::System.StringComparison.Ordinal))
            {
                if (originalNameAttribute != null)
                {
                    return string.Concat("Company.", originalNameAttribute.OriginalName);
                }
                return string.Concat("Company.", clientType.Name);
            }
            if (clientType.Namespace.Equals("Content", global::System.StringComparison.Ordinal))
            {
                if (originalNameAttribute != null)
                {
                    return string.Concat("Content.", originalNameAttribute.OriginalName);
                }
                return string.Concat("Content.", clientType.Name);
            }
            if (clientType.Namespace.Equals("Docflow", global::System.StringComparison.Ordinal))
            {
                if (originalNameAttribute != null)
                {
                    return string.Concat("Docflow.", originalNameAttribute.OriginalName);
                }
                return string.Concat("Docflow.", clientType.Name);
            }
            if (clientType.Namespace.Equals("Parties", global::System.StringComparison.Ordinal))
            {
                if (originalNameAttribute != null)
                {
                    return string.Concat("Parties.", originalNameAttribute.OriginalName);
                }
                return string.Concat("Parties.", clientType.Name);
            }
            if (clientType.Namespace.Equals("Shell", global::System.StringComparison.Ordinal))
            {
                if (originalNameAttribute != null)
                {
                    return string.Concat("Shell.", originalNameAttribute.OriginalName);
                }
                return string.Concat("Shell.", clientType.Name);
            }
            if (originalNameAttribute != null)
            {
                return clientType.Namespace + "." + originalNameAttribute.OriginalName;
            }
            return clientType.FullName;
        }
        /// <summary>
        /// There are no comments for IRecipients in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("IRecipients")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<global::Sungero.IntegrationService.Models.Generated.CoreEntities.IRecipientDto> IRecipients
        {
            get
            {
                if ((this._IRecipients == null))
                {
                    this._IRecipients = base.CreateQuery<global::Sungero.IntegrationService.Models.Generated.CoreEntities.IRecipientDto>("IRecipients");
                }
                return this._IRecipients;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::Sungero.IntegrationService.Models.Generated.CoreEntities.IRecipientDto> _IRecipients;
        /// <summary>
        /// There are no comments for IGroups in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("IGroups")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<global::Sungero.IntegrationService.Models.Generated.CoreEntities.IGroupDto> IGroups
        {
            get
            {
                if ((this._IGroups == null))
                {
                    this._IGroups = base.CreateQuery<global::Sungero.IntegrationService.Models.Generated.CoreEntities.IGroupDto>("IGroups");
                }
                return this._IGroups;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::Sungero.IntegrationService.Models.Generated.CoreEntities.IGroupDto> _IGroups;
        /// <summary>
        /// There are no comments for IBusinessUnits in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("IBusinessUnits")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<global::Sungero.IntegrationService.Models.Generated.Company.IBusinessUnitDto> IBusinessUnits
        {
            get
            {
                if ((this._IBusinessUnits == null))
                {
                    this._IBusinessUnits = base.CreateQuery<global::Sungero.IntegrationService.Models.Generated.Company.IBusinessUnitDto>("IBusinessUnits");
                }
                return this._IBusinessUnits;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::Sungero.IntegrationService.Models.Generated.Company.IBusinessUnitDto> _IBusinessUnits;
        /// <summary>
        /// There are no comments for IDepartments in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("IDepartments")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<global::Sungero.IntegrationService.Models.Generated.Company.IDepartmentDto> IDepartments
        {
            get
            {
                if ((this._IDepartments == null))
                {
                    this._IDepartments = base.CreateQuery<global::Sungero.IntegrationService.Models.Generated.Company.IDepartmentDto>("IDepartments");
                }
                return this._IDepartments;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::Sungero.IntegrationService.Models.Generated.Company.IDepartmentDto> _IDepartments;
        /// <summary>
        /// There are no comments for IUsers in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("IUsers")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<global::Sungero.IntegrationService.Models.Generated.CoreEntities.IUserDto> IUsers
        {
            get
            {
                if ((this._IUsers == null))
                {
                    this._IUsers = base.CreateQuery<global::Sungero.IntegrationService.Models.Generated.CoreEntities.IUserDto>("IUsers");
                }
                return this._IUsers;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::Sungero.IntegrationService.Models.Generated.CoreEntities.IUserDto> _IUsers;
        /// <summary>
        /// There are no comments for IEmployees in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("IEmployees")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<global::Sungero.IntegrationService.Models.Generated.DreamSolution.IEmployeeDto> IEmployees
        {
            get
            {
                if ((this._IEmployees == null))
                {
                    this._IEmployees = base.CreateQuery<global::Sungero.IntegrationService.Models.Generated.DreamSolution.IEmployeeDto>("IEmployees");
                }
                return this._IEmployees;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::Sungero.IntegrationService.Models.Generated.DreamSolution.IEmployeeDto> _IEmployees;
        /// <summary>
        /// There are no comments for ILogins in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("ILogins")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<global::Sungero.IntegrationService.Models.Generated.CoreEntities.ILoginDto> ILogins
        {
            get
            {
                if ((this._ILogins == null))
                {
                    this._ILogins = base.CreateQuery<global::Sungero.IntegrationService.Models.Generated.CoreEntities.ILoginDto>("ILogins");
                }
                return this._ILogins;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::Sungero.IntegrationService.Models.Generated.CoreEntities.ILoginDto> _ILogins;
        /// <summary>
        /// There are no comments for ICertificates in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("ICertificates")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<global::Sungero.IntegrationService.Models.Generated.CoreEntities.ICertificateDto> ICertificates
        {
            get
            {
                if ((this._ICertificates == null))
                {
                    this._ICertificates = base.CreateQuery<global::Sungero.IntegrationService.Models.Generated.CoreEntities.ICertificateDto>("ICertificates");
                }
                return this._ICertificates;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::Sungero.IntegrationService.Models.Generated.CoreEntities.ICertificateDto> _ICertificates;
        /// <summary>
        /// There are no comments for IEmployeeMutationKinds in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("IEmployeeMutationKinds")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<global::Sungero.IntegrationService.Models.Generated.EmployeeModule.IEmployeeMutationKindDto> IEmployeeMutationKinds
        {
            get
            {
                if ((this._IEmployeeMutationKinds == null))
                {
                    this._IEmployeeMutationKinds = base.CreateQuery<global::Sungero.IntegrationService.Models.Generated.EmployeeModule.IEmployeeMutationKindDto>("IEmployeeMutationKinds");
                }
                return this._IEmployeeMutationKinds;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::Sungero.IntegrationService.Models.Generated.EmployeeModule.IEmployeeMutationKindDto> _IEmployeeMutationKinds;
        /// <summary>
        /// There are no comments for ICities in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("ICities")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<global::Sungero.IntegrationService.Models.Generated.Commons.ICityDto> ICities
        {
            get
            {
                if ((this._ICities == null))
                {
                    this._ICities = base.CreateQuery<global::Sungero.IntegrationService.Models.Generated.Commons.ICityDto>("ICities");
                }
                return this._ICities;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::Sungero.IntegrationService.Models.Generated.Commons.ICityDto> _ICities;
        /// <summary>
        /// There are no comments for ICountries in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("ICountries")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<global::Sungero.IntegrationService.Models.Generated.Commons.ICountryDto> ICountries
        {
            get
            {
                if ((this._ICountries == null))
                {
                    this._ICountries = base.CreateQuery<global::Sungero.IntegrationService.Models.Generated.Commons.ICountryDto>("ICountries");
                }
                return this._ICountries;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::Sungero.IntegrationService.Models.Generated.Commons.ICountryDto> _ICountries;
        /// <summary>
        /// There are no comments for IRegions in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("IRegions")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<global::Sungero.IntegrationService.Models.Generated.Commons.IRegionDto> IRegions
        {
            get
            {
                if ((this._IRegions == null))
                {
                    this._IRegions = base.CreateQuery<global::Sungero.IntegrationService.Models.Generated.Commons.IRegionDto>("IRegions");
                }
                return this._IRegions;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::Sungero.IntegrationService.Models.Generated.Commons.IRegionDto> _IRegions;
        /// <summary>
        /// There are no comments for IJobTitles in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("IJobTitles")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<global::Sungero.IntegrationService.Models.Generated.Company.IJobTitleDto> IJobTitles
        {
            get
            {
                if ((this._IJobTitles == null))
                {
                    this._IJobTitles = base.CreateQuery<global::Sungero.IntegrationService.Models.Generated.Company.IJobTitleDto>("IJobTitles");
                }
                return this._IJobTitles;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::Sungero.IntegrationService.Models.Generated.Company.IJobTitleDto> _IJobTitles;
        /// <summary>
        /// There are no comments for IBoxBases in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("IBoxBases")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<global::Sungero.IntegrationService.Models.Generated.ExchangeCore.IBoxBaseDto> IBoxBases
        {
            get
            {
                if ((this._IBoxBases == null))
                {
                    this._IBoxBases = base.CreateQuery<global::Sungero.IntegrationService.Models.Generated.ExchangeCore.IBoxBaseDto>("IBoxBases");
                }
                return this._IBoxBases;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::Sungero.IntegrationService.Models.Generated.ExchangeCore.IBoxBaseDto> _IBoxBases;
        /// <summary>
        /// There are no comments for IBusinessUnitBoxs in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("IBusinessUnitBoxs")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<global::Sungero.IntegrationService.Models.Generated.ExchangeCore.IBusinessUnitBoxDto> IBusinessUnitBoxs
        {
            get
            {
                if ((this._IBusinessUnitBoxs == null))
                {
                    this._IBusinessUnitBoxs = base.CreateQuery<global::Sungero.IntegrationService.Models.Generated.ExchangeCore.IBusinessUnitBoxDto>("IBusinessUnitBoxs");
                }
                return this._IBusinessUnitBoxs;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::Sungero.IntegrationService.Models.Generated.ExchangeCore.IBusinessUnitBoxDto> _IBusinessUnitBoxs;
        /// <summary>
        /// There are no comments for IExchangeServices in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("IExchangeServices")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<global::Sungero.IntegrationService.Models.Generated.ExchangeCore.IExchangeServiceDto> IExchangeServices
        {
            get
            {
                if ((this._IExchangeServices == null))
                {
                    this._IExchangeServices = base.CreateQuery<global::Sungero.IntegrationService.Models.Generated.ExchangeCore.IExchangeServiceDto>("IExchangeServices");
                }
                return this._IExchangeServices;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::Sungero.IntegrationService.Models.Generated.ExchangeCore.IExchangeServiceDto> _IExchangeServices;
        /// <summary>
        /// There are no comments for ICounterpartyKinds in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("ICounterpartyKinds")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<global::Sungero.IntegrationService.Models.Generated.Parties.ICounterpartyKindDto> ICounterpartyKinds
        {
            get
            {
                if ((this._ICounterpartyKinds == null))
                {
                    this._ICounterpartyKinds = base.CreateQuery<global::Sungero.IntegrationService.Models.Generated.Parties.ICounterpartyKindDto>("ICounterpartyKinds");
                }
                return this._ICounterpartyKinds;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::Sungero.IntegrationService.Models.Generated.Parties.ICounterpartyKindDto> _ICounterpartyKinds;
        /// <summary>
        /// There are no comments for ICounterparties in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("ICounterparties")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<global::Sungero.IntegrationService.Models.Generated.Parties.ICounterpartyDto> ICounterparties
        {
            get
            {
                if ((this._ICounterparties == null))
                {
                    this._ICounterparties = base.CreateQuery<global::Sungero.IntegrationService.Models.Generated.Parties.ICounterpartyDto>("ICounterparties");
                }
                return this._ICounterparties;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::Sungero.IntegrationService.Models.Generated.Parties.ICounterpartyDto> _ICounterparties;
        /// <summary>
        /// There are no comments for ICompanyBases in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("ICompanyBases")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<global::Sungero.IntegrationService.Models.Generated.Parties.ICompanyBaseDto> ICompanyBases
        {
            get
            {
                if ((this._ICompanyBases == null))
                {
                    this._ICompanyBases = base.CreateQuery<global::Sungero.IntegrationService.Models.Generated.Parties.ICompanyBaseDto>("ICompanyBases");
                }
                return this._ICompanyBases;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::Sungero.IntegrationService.Models.Generated.Parties.ICompanyBaseDto> _ICompanyBases;
        /// <summary>
        /// There are no comments for IBanks in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("IBanks")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<global::Sungero.IntegrationService.Models.Generated.Parties.IBankDto> IBanks
        {
            get
            {
                if ((this._IBanks == null))
                {
                    this._IBanks = base.CreateQuery<global::Sungero.IntegrationService.Models.Generated.Parties.IBankDto>("IBanks");
                }
                return this._IBanks;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::Sungero.IntegrationService.Models.Generated.Parties.IBankDto> _IBanks;
        /// <summary>
        /// There are no comments for ICompanies in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("ICompanies")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<global::Sungero.IntegrationService.Models.Generated.Parties.ICompanyDto> ICompanies
        {
            get
            {
                if ((this._ICompanies == null))
                {
                    this._ICompanies = base.CreateQuery<global::Sungero.IntegrationService.Models.Generated.Parties.ICompanyDto>("ICompanies");
                }
                return this._ICompanies;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::Sungero.IntegrationService.Models.Generated.Parties.ICompanyDto> _ICompanies;
        /// <summary>
        /// There are no comments for IPersons in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("IPersons")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<global::Sungero.IntegrationService.Models.Generated.Parties.IPersonDto> IPersons
        {
            get
            {
                if ((this._IPersons == null))
                {
                    this._IPersons = base.CreateQuery<global::Sungero.IntegrationService.Models.Generated.Parties.IPersonDto>("IPersons");
                }
                return this._IPersons;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::Sungero.IntegrationService.Models.Generated.Parties.IPersonDto> _IPersons;
        /// <summary>
        /// There are no comments for ICertificateParameterss in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("ICertificateParameterss")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<global::Sungero.IntegrationService.Models.Generated.CoreEntities.ICertificateParameterDto> ICertificateParameterss
        {
            get
            {
                if ((this._ICertificateParameterss == null))
                {
                    this._ICertificateParameterss = base.CreateQuery<global::Sungero.IntegrationService.Models.Generated.CoreEntities.ICertificateParameterDto>("ICertificateParameterss");
                }
                return this._ICertificateParameterss;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::Sungero.IntegrationService.Models.Generated.CoreEntities.ICertificateParameterDto> _ICertificateParameterss;
        /// <summary>
        /// There are no comments for IGroupRecipientLinkss in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("IGroupRecipientLinkss")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<global::Sungero.IntegrationService.Models.Generated.CoreEntities.IGroupRecipientLinksDto> IGroupRecipientLinkss
        {
            get
            {
                if ((this._IGroupRecipientLinkss == null))
                {
                    this._IGroupRecipientLinkss = base.CreateQuery<global::Sungero.IntegrationService.Models.Generated.CoreEntities.IGroupRecipientLinksDto>("IGroupRecipientLinkss");
                }
                return this._IGroupRecipientLinkss;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::Sungero.IntegrationService.Models.Generated.CoreEntities.IGroupRecipientLinksDto> _IGroupRecipientLinkss;
        /// <summary>
        /// There are no comments for IEmployeeMutationsStudents in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("IEmployeeMutationsStudents")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<global::Sungero.IntegrationService.Models.Generated.DreamSolution.IEmployeeMutationsStudentDto> IEmployeeMutationsStudents
        {
            get
            {
                if ((this._IEmployeeMutationsStudents == null))
                {
                    this._IEmployeeMutationsStudents = base.CreateQuery<global::Sungero.IntegrationService.Models.Generated.DreamSolution.IEmployeeMutationsStudentDto>("IEmployeeMutationsStudents");
                }
                return this._IEmployeeMutationsStudents;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::Sungero.IntegrationService.Models.Generated.DreamSolution.IEmployeeMutationsStudentDto> _IEmployeeMutationsStudents;
        /// <summary>
        /// There are no comments for IBusinessUnitBoxExchangeServiceCertificatess in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("IBusinessUnitBoxExchangeServiceCertificatess")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<global::Sungero.IntegrationService.Models.Generated.ExchangeCore.IBusinessUnitBoxExchangeServiceCertificatesDto> IBusinessUnitBoxExchangeServiceCertificatess
        {
            get
            {
                if ((this._IBusinessUnitBoxExchangeServiceCertificatess == null))
                {
                    this._IBusinessUnitBoxExchangeServiceCertificatess = base.CreateQuery<global::Sungero.IntegrationService.Models.Generated.ExchangeCore.IBusinessUnitBoxExchangeServiceCertificatesDto>("IBusinessUnitBoxExchangeServiceCertificatess");
                }
                return this._IBusinessUnitBoxExchangeServiceCertificatess;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::Sungero.IntegrationService.Models.Generated.ExchangeCore.IBusinessUnitBoxExchangeServiceCertificatesDto> _IBusinessUnitBoxExchangeServiceCertificatess;
        /// <summary>
        /// There are no comments for IBusinessUnitBoxFormalizedPoAInfoss in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("IBusinessUnitBoxFormalizedPoAInfoss")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<global::Sungero.IntegrationService.Models.Generated.ExchangeCore.IBusinessUnitBoxFormalizedPoAInfosDto> IBusinessUnitBoxFormalizedPoAInfoss
        {
            get
            {
                if ((this._IBusinessUnitBoxFormalizedPoAInfoss == null))
                {
                    this._IBusinessUnitBoxFormalizedPoAInfoss = base.CreateQuery<global::Sungero.IntegrationService.Models.Generated.ExchangeCore.IBusinessUnitBoxFormalizedPoAInfosDto>("IBusinessUnitBoxFormalizedPoAInfoss");
                }
                return this._IBusinessUnitBoxFormalizedPoAInfoss;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::Sungero.IntegrationService.Models.Generated.ExchangeCore.IBusinessUnitBoxFormalizedPoAInfosDto> _IBusinessUnitBoxFormalizedPoAInfoss;
        /// <summary>
        /// There are no comments for ICounterpartyExchangeBoxess in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("ICounterpartyExchangeBoxess")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<global::Sungero.IntegrationService.Models.Generated.Parties.ICounterpartyExchangeBoxesDto> ICounterpartyExchangeBoxess
        {
            get
            {
                if ((this._ICounterpartyExchangeBoxess == null))
                {
                    this._ICounterpartyExchangeBoxess = base.CreateQuery<global::Sungero.IntegrationService.Models.Generated.Parties.ICounterpartyExchangeBoxesDto>("ICounterpartyExchangeBoxess");
                }
                return this._ICounterpartyExchangeBoxess;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::Sungero.IntegrationService.Models.Generated.Parties.ICounterpartyExchangeBoxesDto> _ICounterpartyExchangeBoxess;
        /// <summary>
        /// There are no comments for IRecipients in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual void AddToIRecipients(global::Sungero.IntegrationService.Models.Generated.CoreEntities.IRecipientDto iRecipientDto)
        {
            base.AddObject("IRecipients", iRecipientDto);
        }
        /// <summary>
        /// There are no comments for IGroups in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual void AddToIGroups(global::Sungero.IntegrationService.Models.Generated.CoreEntities.IGroupDto iGroupDto)
        {
            base.AddObject("IGroups", iGroupDto);
        }
        /// <summary>
        /// There are no comments for IBusinessUnits in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual void AddToIBusinessUnits(global::Sungero.IntegrationService.Models.Generated.Company.IBusinessUnitDto iBusinessUnitDto)
        {
            base.AddObject("IBusinessUnits", iBusinessUnitDto);
        }
        /// <summary>
        /// There are no comments for IDepartments in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual void AddToIDepartments(global::Sungero.IntegrationService.Models.Generated.Company.IDepartmentDto iDepartmentDto)
        {
            base.AddObject("IDepartments", iDepartmentDto);
        }
        /// <summary>
        /// There are no comments for IUsers in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual void AddToIUsers(global::Sungero.IntegrationService.Models.Generated.CoreEntities.IUserDto iUserDto)
        {
            base.AddObject("IUsers", iUserDto);
        }
        /// <summary>
        /// There are no comments for IEmployees in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual void AddToIEmployees(global::Sungero.IntegrationService.Models.Generated.DreamSolution.IEmployeeDto iEmployeeDto)
        {
            base.AddObject("IEmployees", iEmployeeDto);
        }
        /// <summary>
        /// There are no comments for ILogins in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual void AddToILogins(global::Sungero.IntegrationService.Models.Generated.CoreEntities.ILoginDto iLoginDto)
        {
            base.AddObject("ILogins", iLoginDto);
        }
        /// <summary>
        /// There are no comments for ICertificates in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual void AddToICertificates(global::Sungero.IntegrationService.Models.Generated.CoreEntities.ICertificateDto iCertificateDto)
        {
            base.AddObject("ICertificates", iCertificateDto);
        }
        /// <summary>
        /// There are no comments for IEmployeeMutationKinds in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual void AddToIEmployeeMutationKinds(global::Sungero.IntegrationService.Models.Generated.EmployeeModule.IEmployeeMutationKindDto iEmployeeMutationKindDto)
        {
            base.AddObject("IEmployeeMutationKinds", iEmployeeMutationKindDto);
        }
        /// <summary>
        /// There are no comments for ICities in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual void AddToICities(global::Sungero.IntegrationService.Models.Generated.Commons.ICityDto iCityDto)
        {
            base.AddObject("ICities", iCityDto);
        }
        /// <summary>
        /// There are no comments for ICountries in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual void AddToICountries(global::Sungero.IntegrationService.Models.Generated.Commons.ICountryDto iCountryDto)
        {
            base.AddObject("ICountries", iCountryDto);
        }
        /// <summary>
        /// There are no comments for IRegions in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual void AddToIRegions(global::Sungero.IntegrationService.Models.Generated.Commons.IRegionDto iRegionDto)
        {
            base.AddObject("IRegions", iRegionDto);
        }
        /// <summary>
        /// There are no comments for IJobTitles in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual void AddToIJobTitles(global::Sungero.IntegrationService.Models.Generated.Company.IJobTitleDto iJobTitleDto)
        {
            base.AddObject("IJobTitles", iJobTitleDto);
        }
        /// <summary>
        /// There are no comments for IBoxBases in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual void AddToIBoxBases(global::Sungero.IntegrationService.Models.Generated.ExchangeCore.IBoxBaseDto iBoxBaseDto)
        {
            base.AddObject("IBoxBases", iBoxBaseDto);
        }
        /// <summary>
        /// There are no comments for IBusinessUnitBoxs in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual void AddToIBusinessUnitBoxs(global::Sungero.IntegrationService.Models.Generated.ExchangeCore.IBusinessUnitBoxDto iBusinessUnitBoxDto)
        {
            base.AddObject("IBusinessUnitBoxs", iBusinessUnitBoxDto);
        }
        /// <summary>
        /// There are no comments for IExchangeServices in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual void AddToIExchangeServices(global::Sungero.IntegrationService.Models.Generated.ExchangeCore.IExchangeServiceDto iExchangeServiceDto)
        {
            base.AddObject("IExchangeServices", iExchangeServiceDto);
        }
        /// <summary>
        /// There are no comments for ICounterpartyKinds in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual void AddToICounterpartyKinds(global::Sungero.IntegrationService.Models.Generated.Parties.ICounterpartyKindDto iCounterpartyKindDto)
        {
            base.AddObject("ICounterpartyKinds", iCounterpartyKindDto);
        }
        /// <summary>
        /// There are no comments for ICounterparties in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual void AddToICounterparties(global::Sungero.IntegrationService.Models.Generated.Parties.ICounterpartyDto iCounterpartyDto)
        {
            base.AddObject("ICounterparties", iCounterpartyDto);
        }
        /// <summary>
        /// There are no comments for ICompanyBases in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual void AddToICompanyBases(global::Sungero.IntegrationService.Models.Generated.Parties.ICompanyBaseDto iCompanyBaseDto)
        {
            base.AddObject("ICompanyBases", iCompanyBaseDto);
        }
        /// <summary>
        /// There are no comments for IBanks in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual void AddToIBanks(global::Sungero.IntegrationService.Models.Generated.Parties.IBankDto iBankDto)
        {
            base.AddObject("IBanks", iBankDto);
        }
        /// <summary>
        /// There are no comments for ICompanies in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual void AddToICompanies(global::Sungero.IntegrationService.Models.Generated.Parties.ICompanyDto iCompanyDto)
        {
            base.AddObject("ICompanies", iCompanyDto);
        }
        /// <summary>
        /// There are no comments for IPersons in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual void AddToIPersons(global::Sungero.IntegrationService.Models.Generated.Parties.IPersonDto iPersonDto)
        {
            base.AddObject("IPersons", iPersonDto);
        }
        /// <summary>
        /// There are no comments for ICertificateParameterss in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual void AddToICertificateParameterss(global::Sungero.IntegrationService.Models.Generated.CoreEntities.ICertificateParameterDto iCertificateParameterDto)
        {
            base.AddObject("ICertificateParameterss", iCertificateParameterDto);
        }
        /// <summary>
        /// There are no comments for IGroupRecipientLinkss in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual void AddToIGroupRecipientLinkss(global::Sungero.IntegrationService.Models.Generated.CoreEntities.IGroupRecipientLinksDto iGroupRecipientLinksDto)
        {
            base.AddObject("IGroupRecipientLinkss", iGroupRecipientLinksDto);
        }
        /// <summary>
        /// There are no comments for IEmployeeMutationsStudents in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual void AddToIEmployeeMutationsStudents(global::Sungero.IntegrationService.Models.Generated.DreamSolution.IEmployeeMutationsStudentDto iEmployeeMutationsStudentDto)
        {
            base.AddObject("IEmployeeMutationsStudents", iEmployeeMutationsStudentDto);
        }
        /// <summary>
        /// There are no comments for IBusinessUnitBoxExchangeServiceCertificatess in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual void AddToIBusinessUnitBoxExchangeServiceCertificatess(global::Sungero.IntegrationService.Models.Generated.ExchangeCore.IBusinessUnitBoxExchangeServiceCertificatesDto iBusinessUnitBoxExchangeServiceCertificatesDto)
        {
            base.AddObject("IBusinessUnitBoxExchangeServiceCertificatess", iBusinessUnitBoxExchangeServiceCertificatesDto);
        }
        /// <summary>
        /// There are no comments for IBusinessUnitBoxFormalizedPoAInfoss in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual void AddToIBusinessUnitBoxFormalizedPoAInfoss(global::Sungero.IntegrationService.Models.Generated.ExchangeCore.IBusinessUnitBoxFormalizedPoAInfosDto iBusinessUnitBoxFormalizedPoAInfosDto)
        {
            base.AddObject("IBusinessUnitBoxFormalizedPoAInfoss", iBusinessUnitBoxFormalizedPoAInfosDto);
        }
        /// <summary>
        /// There are no comments for ICounterpartyExchangeBoxess in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual void AddToICounterpartyExchangeBoxess(global::Sungero.IntegrationService.Models.Generated.Parties.ICounterpartyExchangeBoxesDto iCounterpartyExchangeBoxesDto)
        {
            base.AddObject("ICounterpartyExchangeBoxess", iCounterpartyExchangeBoxesDto);
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private abstract class GeneratedEdmModel
        {
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
            private static global::Microsoft.OData.Edm.IEdmModel ParsedModel = LoadModelFromString();

            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
            private const string filePath = @"DirectumCsdl.xml";

            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
            public static global::Microsoft.OData.Edm.IEdmModel GetInstance()
            {
                return ParsedModel;
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
            private static global::Microsoft.OData.Edm.IEdmModel LoadModelFromString()
            {
                global::System.Xml.XmlReader reader = CreateXmlReader();
                try
                {
                    global::System.Collections.Generic.IEnumerable<global::Microsoft.OData.Edm.Validation.EdmError> errors;
                    global::Microsoft.OData.Edm.IEdmModel edmModel;

                    if (!global::Microsoft.OData.Edm.Csdl.CsdlReader.TryParse(reader, true, out edmModel, out errors))
                    {
	                    global::System.Text.StringBuilder errorMessages = new global::System.Text.StringBuilder();
	                    foreach (var error in errors)
	                    {
		                    errorMessages.Append(error.ErrorMessage);
		                    errorMessages.Append("; ");
	                    }
	                    throw new global::System.InvalidOperationException(errorMessages.ToString());
                    }

                    return edmModel;
                }
                finally
                {
                    ((global::System.IDisposable)(reader)).Dispose();
                }
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
            private static global::System.Xml.XmlReader CreateXmlReader(string edmxToParse)
            {
                return global::System.Xml.XmlReader.Create(new global::System.IO.StringReader(edmxToParse));
            }

            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
            private static global::System.Xml.XmlReader CreateXmlReader()
            {
                try
                {
                    var assembly = global::System.Reflection.Assembly.GetExecutingAssembly();
                    var resourcePath = global::System.Linq.Enumerable.Single(assembly.GetManifestResourceNames(), str => str.EndsWith(filePath));
                    global::System.IO.Stream stream = assembly.GetManifestResourceStream(resourcePath);
                    return global::System.Xml.XmlReader.Create(new global::System.IO.StreamReader(stream));
                }
                catch(global::System.Xml.XmlException e)
                {
                    throw new global::System.Xml.XmlException("Failed to create an XmlReader from the stream. Check if the resource exists.", e);
                }
            }
        }
    }
}
