//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generation date: 26.11.2023 2:59:27
namespace Sungero.IntegrationService.Models.Generated.ExchangeCore
{
    /// <summary>
    /// Class containing all extension methods
    /// </summary>
    public static class ExtensionMethods
    {
        /// <summary>
        /// Get an entity of type global::Sungero.IntegrationService.Models.Generated.ExchangeCore.IBoxBaseDto as global::Sungero.IntegrationService.Models.Generated.ExchangeCore.IBoxBaseDtoSingle specified by key from an entity set
        /// </summary>
        /// <param name="_source">source entity set</param>
        /// <param name="_keys">dictionary with the names and values of keys</param>
        public static global::Sungero.IntegrationService.Models.Generated.ExchangeCore.IBoxBaseDtoSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::Sungero.IntegrationService.Models.Generated.ExchangeCore.IBoxBaseDto> _source, global::System.Collections.Generic.IDictionary<string, object> _keys)
        {
            return new global::Sungero.IntegrationService.Models.Generated.ExchangeCore.IBoxBaseDtoSingle(_source.Context, _source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(_source.Context, _keys)));
        }
        /// <summary>
        /// Get an entity of type global::Sungero.IntegrationService.Models.Generated.ExchangeCore.IBoxBaseDto as global::Sungero.IntegrationService.Models.Generated.ExchangeCore.IBoxBaseDtoSingle specified by key from an entity set
        /// </summary>
        /// <param name="_source">source entity set</param>
        /// <param name="id">The value of id</param>
        public static global::Sungero.IntegrationService.Models.Generated.ExchangeCore.IBoxBaseDtoSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::Sungero.IntegrationService.Models.Generated.ExchangeCore.IBoxBaseDto> _source,
            long id)
        {
            global::System.Collections.Generic.IDictionary<string, object> _keys = new global::System.Collections.Generic.Dictionary<string, object>
            {
                { "Id", id }
            };
            return new global::Sungero.IntegrationService.Models.Generated.ExchangeCore.IBoxBaseDtoSingle(_source.Context, _source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(_source.Context, _keys)));
        }
        /// <summary>
        /// Get an entity of type global::Sungero.IntegrationService.Models.Generated.ExchangeCore.IBusinessUnitBoxDto as global::Sungero.IntegrationService.Models.Generated.ExchangeCore.IBusinessUnitBoxDtoSingle specified by key from an entity set
        /// </summary>
        /// <param name="_source">source entity set</param>
        /// <param name="_keys">dictionary with the names and values of keys</param>
        public static global::Sungero.IntegrationService.Models.Generated.ExchangeCore.IBusinessUnitBoxDtoSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::Sungero.IntegrationService.Models.Generated.ExchangeCore.IBusinessUnitBoxDto> _source, global::System.Collections.Generic.IDictionary<string, object> _keys)
        {
            return new global::Sungero.IntegrationService.Models.Generated.ExchangeCore.IBusinessUnitBoxDtoSingle(_source.Context, _source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(_source.Context, _keys)));
        }
        /// <summary>
        /// Get an entity of type global::Sungero.IntegrationService.Models.Generated.ExchangeCore.IBusinessUnitBoxDto as global::Sungero.IntegrationService.Models.Generated.ExchangeCore.IBusinessUnitBoxDtoSingle specified by key from an entity set
        /// </summary>
        /// <param name="_source">source entity set</param>
        /// <param name="id">The value of id</param>
        public static global::Sungero.IntegrationService.Models.Generated.ExchangeCore.IBusinessUnitBoxDtoSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::Sungero.IntegrationService.Models.Generated.ExchangeCore.IBusinessUnitBoxDto> _source,
            long id)
        {
            global::System.Collections.Generic.IDictionary<string, object> _keys = new global::System.Collections.Generic.Dictionary<string, object>
            {
                { "Id", id }
            };
            return new global::Sungero.IntegrationService.Models.Generated.ExchangeCore.IBusinessUnitBoxDtoSingle(_source.Context, _source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(_source.Context, _keys)));
        }
        /// <summary>
        /// Cast an entity of type global::Sungero.IntegrationService.Models.Generated.ExchangeCore.IBoxBaseDto to its derived type global::Sungero.IntegrationService.Models.Generated.ExchangeCore.IBusinessUnitBoxDto
        /// </summary>
        /// <param name="_source">source entity</param>
        public static global::Sungero.IntegrationService.Models.Generated.ExchangeCore.IBusinessUnitBoxDtoSingle CastToIBusinessUnitBoxDto(this global::Microsoft.OData.Client.DataServiceQuerySingle<global::Sungero.IntegrationService.Models.Generated.ExchangeCore.IBoxBaseDto> _source)
        {
            global::Microsoft.OData.Client.DataServiceQuerySingle<global::Sungero.IntegrationService.Models.Generated.ExchangeCore.IBusinessUnitBoxDto> query = _source.CastTo<global::Sungero.IntegrationService.Models.Generated.ExchangeCore.IBusinessUnitBoxDto>();
            return new global::Sungero.IntegrationService.Models.Generated.ExchangeCore.IBusinessUnitBoxDtoSingle(_source.Context, query.GetPath(null));
        }
        /// <summary>
        /// Get an entity of type global::Sungero.IntegrationService.Models.Generated.ExchangeCore.IExchangeServiceDto as global::Sungero.IntegrationService.Models.Generated.ExchangeCore.IExchangeServiceDtoSingle specified by key from an entity set
        /// </summary>
        /// <param name="_source">source entity set</param>
        /// <param name="_keys">dictionary with the names and values of keys</param>
        public static global::Sungero.IntegrationService.Models.Generated.ExchangeCore.IExchangeServiceDtoSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::Sungero.IntegrationService.Models.Generated.ExchangeCore.IExchangeServiceDto> _source, global::System.Collections.Generic.IDictionary<string, object> _keys)
        {
            return new global::Sungero.IntegrationService.Models.Generated.ExchangeCore.IExchangeServiceDtoSingle(_source.Context, _source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(_source.Context, _keys)));
        }
        /// <summary>
        /// Get an entity of type global::Sungero.IntegrationService.Models.Generated.ExchangeCore.IExchangeServiceDto as global::Sungero.IntegrationService.Models.Generated.ExchangeCore.IExchangeServiceDtoSingle specified by key from an entity set
        /// </summary>
        /// <param name="_source">source entity set</param>
        /// <param name="id">The value of id</param>
        public static global::Sungero.IntegrationService.Models.Generated.ExchangeCore.IExchangeServiceDtoSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::Sungero.IntegrationService.Models.Generated.ExchangeCore.IExchangeServiceDto> _source,
            long id)
        {
            global::System.Collections.Generic.IDictionary<string, object> _keys = new global::System.Collections.Generic.Dictionary<string, object>
            {
                { "Id", id }
            };
            return new global::Sungero.IntegrationService.Models.Generated.ExchangeCore.IExchangeServiceDtoSingle(_source.Context, _source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(_source.Context, _keys)));
        }
        /// <summary>
        /// Get an entity of type global::Sungero.IntegrationService.Models.Generated.ExchangeCore.IBusinessUnitBoxExchangeServiceCertificatesDto as global::Sungero.IntegrationService.Models.Generated.ExchangeCore.IBusinessUnitBoxExchangeServiceCertificatesDtoSingle specified by key from an entity set
        /// </summary>
        /// <param name="_source">source entity set</param>
        /// <param name="_keys">dictionary with the names and values of keys</param>
        public static global::Sungero.IntegrationService.Models.Generated.ExchangeCore.IBusinessUnitBoxExchangeServiceCertificatesDtoSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::Sungero.IntegrationService.Models.Generated.ExchangeCore.IBusinessUnitBoxExchangeServiceCertificatesDto> _source, global::System.Collections.Generic.IDictionary<string, object> _keys)
        {
            return new global::Sungero.IntegrationService.Models.Generated.ExchangeCore.IBusinessUnitBoxExchangeServiceCertificatesDtoSingle(_source.Context, _source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(_source.Context, _keys)));
        }
        /// <summary>
        /// Get an entity of type global::Sungero.IntegrationService.Models.Generated.ExchangeCore.IBusinessUnitBoxExchangeServiceCertificatesDto as global::Sungero.IntegrationService.Models.Generated.ExchangeCore.IBusinessUnitBoxExchangeServiceCertificatesDtoSingle specified by key from an entity set
        /// </summary>
        /// <param name="_source">source entity set</param>
        /// <param name="id">The value of id</param>
        public static global::Sungero.IntegrationService.Models.Generated.ExchangeCore.IBusinessUnitBoxExchangeServiceCertificatesDtoSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::Sungero.IntegrationService.Models.Generated.ExchangeCore.IBusinessUnitBoxExchangeServiceCertificatesDto> _source,
            long id)
        {
            global::System.Collections.Generic.IDictionary<string, object> _keys = new global::System.Collections.Generic.Dictionary<string, object>
            {
                { "Id", id }
            };
            return new global::Sungero.IntegrationService.Models.Generated.ExchangeCore.IBusinessUnitBoxExchangeServiceCertificatesDtoSingle(_source.Context, _source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(_source.Context, _keys)));
        }
        /// <summary>
        /// Get an entity of type global::Sungero.IntegrationService.Models.Generated.ExchangeCore.IBusinessUnitBoxFormalizedPoAInfosDto as global::Sungero.IntegrationService.Models.Generated.ExchangeCore.IBusinessUnitBoxFormalizedPoAInfosDtoSingle specified by key from an entity set
        /// </summary>
        /// <param name="_source">source entity set</param>
        /// <param name="_keys">dictionary with the names and values of keys</param>
        public static global::Sungero.IntegrationService.Models.Generated.ExchangeCore.IBusinessUnitBoxFormalizedPoAInfosDtoSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::Sungero.IntegrationService.Models.Generated.ExchangeCore.IBusinessUnitBoxFormalizedPoAInfosDto> _source, global::System.Collections.Generic.IDictionary<string, object> _keys)
        {
            return new global::Sungero.IntegrationService.Models.Generated.ExchangeCore.IBusinessUnitBoxFormalizedPoAInfosDtoSingle(_source.Context, _source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(_source.Context, _keys)));
        }
        /// <summary>
        /// Get an entity of type global::Sungero.IntegrationService.Models.Generated.ExchangeCore.IBusinessUnitBoxFormalizedPoAInfosDto as global::Sungero.IntegrationService.Models.Generated.ExchangeCore.IBusinessUnitBoxFormalizedPoAInfosDtoSingle specified by key from an entity set
        /// </summary>
        /// <param name="_source">source entity set</param>
        /// <param name="id">The value of id</param>
        public static global::Sungero.IntegrationService.Models.Generated.ExchangeCore.IBusinessUnitBoxFormalizedPoAInfosDtoSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::Sungero.IntegrationService.Models.Generated.ExchangeCore.IBusinessUnitBoxFormalizedPoAInfosDto> _source,
            long id)
        {
            global::System.Collections.Generic.IDictionary<string, object> _keys = new global::System.Collections.Generic.Dictionary<string, object>
            {
                { "Id", id }
            };
            return new global::Sungero.IntegrationService.Models.Generated.ExchangeCore.IBusinessUnitBoxFormalizedPoAInfosDtoSingle(_source.Context, _source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(_source.Context, _keys)));
        }
    }
}
